### ISSUE TITLE
When Thorium launches, we sometimes briefly see legacy menu bar flashing

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1122]
Every once in a while, when I launch Thorium, we can briefly see a legacy menu bar flashing (File, Edit, View, Window, Help) before it gets covered with the final menu bar (My Books, Catalogs, Settings).

<img width="699" alt="Untitled" src="https://user-images.githubusercontent.com/36426806/87765391-bd902480-c7e5-11ea-9b1b-424bd4cdbca9.png">

It is not a bug per say as it does not affect Thorium in any way, so I guess it would fall under a cosmetic issue.

**Comment by danielweck** [comment]
Interesting UI bug, thank you :)
Note that the automated builds include a developer menu item, whereas the official releases do not.

**Comment by danielweck** [comment]
Note that MacOS is an exception, given the prominent nature of application menus in the window manager.
But otherwise, Windows and Linux builds should have no menu bar at all in official releases / production builds.
Code reference: https://github.com/edrlab/thorium-reader/blob/develop/src/main/menu.ts

**Comment by danielweck** [comment]
We haven't been able to reproduce this rendering bug in Electron's recent versions, and we wouldn't be able to fix it anyway in Thorium's code. Closing (bug triage).
