### ISSUE TITLE
Trying to open (import) several EPUBs at once gives an error

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1124]
From Windows File Explorer, selecting multiple EPUBs and pressing enter produces the following error message:

![image](https://user-images.githubusercontent.com/36426806/87776795-56c73700-c7f6-11ea-9979-ff5009653e52.png)

After clicking on [OK], Thorium successfully imports and opens _only_ the last EPUB of the entire set of selected EPUBs.

**Comment by panaC** [comment]
this should be specific to MS windows. it's works on macOs.

**Comment by PhilippeBruno** [comment]
Keep in mind I am using v1.3.1-alpha.1.138 on Windows 10.

**Comment by danielweck** [comment]
Possibly related issue: https://github.com/edrlab/thorium-reader/issues/1123

**Comment by panaC** [comment]
partially fixed with #1221.

No error occurs , it just imports and reads the first publication.

The problem should come from the yargs package implementation to handle Command Line.

https://github.com/edrlab/thorium-reader/blob/1d16f7391a473b207bc23c4413afa55a59ca50ea/src/main/cli/process.ts#L209-L249

all paths from "open with" command are concatenates in the argument line.

https://github.com/yargs/yargs/blob/master/docs/advanced.md#variadic-positional-arguments
https://github.com/yargs/yargs/blob/master/docs/api.md#positionalkey-opt

**Comment by editadapt** [comment]
I have a similar error under windows 10, from Windows File Explorer, opening multiple EPUBs produces a different Error if Thorium is closed or open (see attached screenshots).  Then open the first publication (sometime the second two) as described in fix #1221.
![Screenshots detailling Thorium Errors](https://user-images.githubusercontent.com/38312303/103490886-27959800-4e1f-11eb-9d31-3fe894084b49.png)

**Comment by panaC** [comment]
this feature is actually not implemented. Thorium can only open one file from Windows File Explorer.

**Comment by danielweck** [comment]
This certainly needs fixing (i.e. command line and/or file explorer "open with" of multiple publications), but in the interim, drag-and-drop of multiple files works, as well as using the "import" button from an already-opened Thorium library window (if I remember correctly the file chooser supports multiple selections)

**Comment by panaC** [comment]
yep we will do it. yargs is a bit whimsical to use :)
