### ISSUE TITLE
[PDF] pdf page scale (zoom) need to be more precise

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1192]
**Currently :**

![image](https://user-images.githubusercontent.com/3198865/94909652-c965bb80-04a3-11eb-98d7-348b46caad0a.png)

the zoom value isn't precise and need more steps.

**Expected result :**

the same behavior that the mozilla demo viewer https://mozilla.github.io/pdf.js/web/viewer.html

![image](https://user-images.githubusercontent.com/3198865/94909822-0a5dd000-04a4-11eb-8ad8-aa8120084c06.png)

**how to fix it :**

file: https://github.com/edrlab/thorium-reader/blob/fa17ec90f5c15091f4b463a930a303610fd28dc4/src/renderer/reader/pdf/webview/pdfReader.ts

PDF Pull Request : #1188

@danielweck https://github.com/edrlab/thorium-reader/pull/1188#issuecomment-700834600

**Comment by llemeurfr** [comment]
I'll argue for the opposite way: the page scale possibilities should be less flexible, but easier to use. This is true both for FXL EPUB and PDF. 

My take is that the reading settings in the side panel are often set once for all, and may be adapted to a given book when reading the first page. For reflowable content it means setting the font, font side, theme... For FXL in means setting the spread and scroll/paginated. 

Scale on FXL is different: reader will need to change the scale often because they want to see the whole page at certain times, then "go deep" into the content to read it easily, then go back to the whole page. 

Therefore I only see two interesting scales: page fit and page width. But the trigger (the affordance) should be directly in the FXL view, not in the side panel (invisible and only accessible via a set of mouse clicks or a ctrl key + a choice). This is what e.g. Izneo offers (see e.g. this [bande dessinée](https://www.izneo.com/en/graphic-novel/action-adventure/avatar-the-last-airbender-katara-and-the-pirate-s-silver-36100/avatar-the-last-airbender-katara-and-the-pirate-s-silver-82669/read/1))
