### ISSUE TITLE
Library disappears after update

### ISSUE THREAD

**Issue by sukiletxe** [edrlab/thorium-reader#1210]
I downloaded an alpha version a couple of days ago to be on bleeding edge code. (Turns out there is no auto update function, but that doesn't bother me much).
Today I dowloaded and installed over v1.5.0 released yesterday and my books disappeared from the database. In C:\users\<user>\App Data\Roaming\EDRLab.ThoriumReader there is no "publications" folder, but a "publications-dev" folder with the books. So fine, I remove the empty publications folder and rename the other one. But my books are gone from Thorium. They have gone only from the database, as they are in the folder.
How can I make it rescan the folder (I would rather not import 18 publications by hand again)?
Thanks!

**Comment by danielweck** [comment]
Hello, the official version 1.5.0 "production" release ( https://github.com/edrlab/thorium-reader/releases/tag/v1.5.0 ) continues to use the `publications` folder, however the automated "development" builds indeed now make use of the `publication-dev` folder:
https://github.com/edrlab/thorium-reader/releases/tag/latest-windows
https://github.com/edrlab/thorium-reader/releases/tag/latest-osx
https://github.com/edrlab/thorium-reader/releases/tag/latest-linux

If you are using the "development" builds of Thorium, I am sorry but you indeed must re-import your EPUB files into the library (select all + drag and drop, for bulk importing)

Note that the "production" and "development" builds have always had separate databases, but they were sharing the same `publication` folder. This was a bug, thus why we fixed it.

**Comment by danielweck** [comment]
I am closing this issue now, but do not hesitate to re-open / continue the discussion if you have follow-up remarks / questions :)

**Comment by sukiletxe** [comment]
The situation was the reverse, I had alpha, then switched to stable with the publications missing, then switched again to Alpha. Now all is in order, I have the books imported again. I didn't import them, I just installed the alpha version.

Have you considered merging the databases, or importing one into the other, or issuing a warning if another one is detected during installation?

**Comment by danielweck** [comment]
I think in the early history of the Thorium project (previously called `readium-desktop`), the databases were intentionally separated for "production" vs. "development" usage, but the mistake was to store publications in the same folder. This is now harmonized (since v1.4, if I remember correctly). Note that the database backend / adapter in "development" builds (SQLite3) is actually different from the "production" backend (LevelDown). So the files cannot simply be copied over, there would need to be some code to perform the migration/duplication. This code would need to be a separate utility, because right now in Thorium builds the databases backends are mutually exclusive at runtime (and therefore at compile / build time too).
