### ISSUE TITLE
Add an action which removes an ebook from "resume reading"

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1211]
Once an ebook has been open, it is currently forever in the "resume reading" selection.

**Comment by danielweck** [comment]
On the whole, I personally find the bookshelf user experience very confusing and somewhat frustrating. Often, recently-read books do not show "first" in the horizontal lists. Whenever I import publications (drag-n-drop, OPDS, etc.) I have to manually scroll and visually scan in order to find them. The PDf/audiobook/normal EPUB classification is useful, but it would also be beneficial to display an alternative resume section for "recently read / accessed" publications, regardless of their type.

**Comment by llemeurfr** [comment]
After discussion, if a publication was not open for a long time and other publications have been opened more recently, this publication disappears from the "resume reading" selection.
