### ISSUE TITLE
Windows code signing with EV Extended Validation Certificate

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1217]
Related: https://github.com/edrlab/thorium-reader/issues/261
Related: https://github.com/edrlab/thorium-reader/issues/97

**Comment by llemeurfr** [comment]
Some notes:

Windows app packagees must be signed, as explained in a [Code-signing best practices document](https://docs.microsoft.com/en-us/previous-versions/windows/hardware/design/dn653556(v=vs.85)) and in [Signing Package, Overview](https://docs.microsoft.com/en-us/windows/msix/package/signing-package-overview). It can be achieved either via SignTool or DeviceGuard signing. 

The use of SignTool to sign an appx is described [here](https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool). SignTool works on a W10 PC. The certificate used to sign your app must be either a .pfx file or be installed in a certificate store. 

The most up-to-date list of CAs (Certificate Authorities) recognized by Microsoft is found [here](https://ccadb-public.secure.force.com/microsoft/IncludedCACertificateReportForMSFT). 

There are two variants of a code signing certificate:

- Standard Code Signing
- Extended Validation (EV) Code Signing

For instance comodossl's lower price is 70 USD/yr for a standard cert and 266 USD/ye for an EV cert ([source](https://comodosslstore.com/code-signing/microsoft-authenticode)). 

An EV (Extension Validation) Certificate is an X.509 certificate. It must be signed by a certificate authority which will require verification of the requesting entity's legal identity before certificate issuance.

EV code signing requires more extensive vetting, but it pays off in the form of a reputation boost with Microsoft SmartScreen filter, and your private key comes stored on an external hardware token for better security. This is a great option for newer developers ([source comodossl](https://comodosslstore.com/resources/what-is-microsoft-authenticode-code-signing-certificate)).

I've found a list of EV Certificate providers [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#extended-validation-code-signing-certificates). 

ssl.com -> 249 USD/yr if 3 yrs
comodossl -> 266 USD/yer if 3 years, with hardw token 
certum -> 266 €/yr if 3 yrs
entrust -> 299 USD/yr min, contact sales
sectigo -> 299 €/yr if 3 yrs
globalsign -> 309 €/yr if x yrs
digicert -> 664 USD/yr if 3 yrs, with hardw token

Note: since the private key is stored on the hardware token, for security it cannot be copied or exported to create a PFX file. ([source](https://comodosslstore.com/code-signing/comodo-ev-code-signing-certificate)). I hope this is not an issue when using SignTool.

**Comment by danielweck** [comment]
> I hope this is not an issue when using SignTool.

I guess it depends on the hardware token, e.g.
https://www.digicert.com/kb/code-signing/ev-authenticode-certificates.htm

**Comment by danielweck** [comment]
Tested with USB hardware token (private key for SSL.com EV code signing certificate).
Works fine in VirtualBox Windows 10 Pro virtual machine.

**Comment by danielweck** [comment]
Note that the imminent version 1.6 release of Thorium for Windows will be code-signed. Expected deployment within the next 24 hours.
