### ISSUE TITLE
Feature request: Fixed layout epub zoom

### ISSUE THREAD

**Issue by MattiJarvinen** [edrlab/thorium-reader#1228]
Most of my ebooks are fixed layout epub3 magazines. A lot of the text is too small to be easily readable and since it is fixed layout epub font size change doesn't do anything ( it would break the laoyout if it would ).

Could Thorium detect if epub is fixed layout and then use css "transform: scale()" to zoom in like with PDFs.

**Comment by danielweck** [comment]
Yes, this feature is planned.

**Comment by llemeurfr** [comment]
Let's merge #1406 with this one, older: 

EPUB 3 fixed layout pages are presented in "fit to page" mode. When the writing is small compared to the screen size, reading can become cumbersome. This is especially true with comics.

It would be good to add for EPUB 3 FXL a feature we developed for PDF, i.e. an affordance which allows selecting fit to page vs fit to width. Because computer screens are in landscape mode and individual pages are in portrait mode, these two modes seem sufficient for making readers happy.

In fit to width mode, the user would just scroll vertically to move through the page(s), just like in the PDF case.

I'm personally less convinced by a configurable zoom (100%, 200%): this requires more user controls for non obvious UX advantages. (but this can be discussed).

**Comment by llemeurfr** [comment]
Related issue: #578

**Comment by kylemarkwilliams** [comment]
Is there any update on this feature?

**Comment by llemeurfr** [comment]
Currently, the dev team is focusing on the technical debt (i.e. solving annoying bugs in the v1.7). This added feature is in the roadmap and will be treated in the next "feature-full" version (1.8). September if possible.

**Comment by danielweck** [comment]
A zoom feature for fixed-layout documents is now available in Thorium. This will be released soon in v1.7.2, but in the meantime feel free to try the feature using an automated build:
https://github.com/edrlab/thorium-reader/releases
(build in progress: https://github.com/edrlab/thorium-reader/actions/runs/1177677791 )

The zoom button in the toolbar can be clicked to cycle through a short predefined list of scaling values (with a special step for "fit into view"). The mouse wheel / trackpad scroll gesture can also be used when hovering on top of this button, to increase/decrease by steps of 10% zoom level. Note that MacOS "natural" direction can be quite counter-intuitive (I am not sure how to handle this in HTML/JS, as the DOM events don't convey the change of direction). Also note that MacOS typical fast-firing kinetic events (even when barely swiping / flinging the trackpad) caused implementation headaches due to how hugely the stream of events differ from a typical mouse wheel "clicky" discrete steps ... the current Thorium UX is not great (there is some event throttling and debouncing in order to filter out noise from the scroll / touch / wheel gestures), but we now have a reasonable compromise that seems to work for multiple input devices.

Lastly, ideally Thorium would support zooming/scrolling/panning etc. directly by interacting with the document's surface (rather than somewhere else in the GUI), but this is technically tricky to implement due to how Thorium's webviews are sandboxed / secured. There is also the thorny issue of interfering with authored scripted interactions, which are very common in fixed layout publications. So in this iteration the UX is rudimentary, but hopefully the underlying zooming mechanics are robust. Tests welcome :) (2-page spread FXL layout in particular, with left/right/center slots)

<img width="912" alt="Screenshot 2021-08-28 at 19 23 50" src="https://user-images.githubusercontent.com/625201/131227356-f2c4f151-40d6-4845-8024-fc2fcaf4c5f2.png">

<img width="912" alt="Screenshot 2021-08-28 at 19 24 32" src="https://user-images.githubusercontent.com/625201/131227394-a2f2ad83-c707-4b35-96fd-0bd0bbd0347f.png">

**Comment by awissam** [comment]
g8 news
thanks a lot
when the final release?

**Comment by awissam** [comment]
when will be the final release?

**Comment by danielweck** [comment]
last night :)

https://github.com/edrlab/thorium-reader/releases/tag/v1.7.2

**Comment by kylemarkwilliams** [comment]
Awesome work @danielweck @llemeurfr. 

One thing I've noticed is that when I zoom in on my epubs they become pixelated and the text becomes hard to read. Is there any solution to this?

**Comment by danielweck** [comment]
Hello, could you please post a separate issue including screenshots? Would you mind sharing your EPUB with me so I can investigate? ( daniel.weck@gmail.com )

**Comment by awissam** [comment]
i confirm, same issue, when i zoom it lost in resolution

**Comment by danielweck** [comment]
The issue of pixelated zoomed viewport was fixed a while back, but I see there was no direct response here. Thus my chiming in, a year on :) 

I also filed this issue to record @ImportTaste 's comment:

https://github.com/edrlab/thorium-reader/issues/1825

**Comment by MooglyGuy** [comment]
Have I inadvertently borrowed Doc Brown's flux-capacitor-retrofit DeLorean DMC-12 and ended up in a timeline where this whole issue thread didn't happen? Because I'm on the latest version of Thorium for x64 Windows and I have no options for zooming whatsoever.

I actually ran across this thread in a Google search for the words "thorium reader zoom", because there are no obvious ways to actually zoom in to what I'm trying to read. Ctrl, Left-Shift, Left-Alt, all combined with mouse-wheel don't seem to do it. Ctrl+Plus/Minus don't do it, either.

I would really appreciate it if someone from the development team, or at least a helpful community member, could take the time to reply and tell me what I'm doing wrong, because I'd assume (as a fellow FOSS dev) that this would be such a boilerplate UI/UX feature for an application like Thorium that I must just be going all Neanderthal-brain and not finding what I'd assume is an existing feature.

![thorium](https://github.com/user-attachments/assets/b79e8803-324f-4565-b5ed-2e451252e209)

**Comment by MooglyGuy** [comment]
It's a non-fixed-layout EPUB, so that would explain the behavior I'm seeing.

![epub](https://github.com/user-attachments/assets/1195d0ce-d465-4d4b-9b7e-4ed871b8e32a)

Funny enough, I already had SumatraPDF installed and have been using it for the past couple of hours, Great minds think alike and all that. :)

I appreciate the reply, and I hope that at some point the Thorium folks can come up with a solution for this, because in my brief interactions with it, Thorium has a much slicker interface and it actually acknowledges my system color-theme settings. Here's to hoping! 🥂

**Comment by MooglyGuy** [comment]
> I think the idea is you're supposed to click on the Aa icon and just make the text bigger to suit your needs.

Well I'll be God-damnit-all-damned. Somehow I totally missed that particular modal for adjusting layout parameters.

Worked like a charm. Thank you so much, glad to not have to resort to Sumatra for reading. All of my dumbassery aside, in the event that you're a dev, major props for the great UI/UX that Thorium has.

![thorium2](https://github.com/user-attachments/assets/c464bc07-7dda-44af-80c8-98cc2d4cd9fb)

**Comment by danielweck** [comment]
Thank you for your feedback, and sorry that some features are not easy to discover "instinctively".  We are also aware that touch pinch/stretch or more complete support for mouse scroll wheel (with a keyboard modifier) would reduce the user experience friction. Currently the zoom feature for both fixed-layout and reflowable publications is quite limited and not user-friendly.
