### ISSUE TITLE
10gb+ size of EDRLab.ThoriumReader\db\config folder on windows

### ISSUE THREAD

**Issue by pashaie** [edrlab/thorium-reader#1274]
After opening any books, there is 10s of gb in EDRLab.ThoriumReader\db\config
I also uninstalled and reinstalled ThoriumReader multiple times but same thing happens.

ThoriumReader ver: 1.5.0
OS: win 10

**Comment by danielweck** [comment]
Wow, this is horrible. This issue is frustrating because version 1.4 introduced a change that was supposed to fix the uncontrolled DB growth (simply by calling the existing PouchDB `compact()` function):

https://github.com/edrlab/thorium-reader/blob/e5fe7f1239aaa9f32c9fe74a0b4f6e08f01e4ed6/src/main/di.ts#L163-L177

https://github.com/edrlab/thorium-reader/blob/e5fe7f1239aaa9f32c9fe74a0b4f6e08f01e4ed6/src/main/redux/sagas/app.ts#L104-L105

Evidently, something is not quite right in the LevelDown adapter (we had a similar issue with the SQLite3 adapter which is used only in non-production builds, i.e. when testing locally, or when using the automated CI builds from the GitHub "releases" section)

**Comment by danielweck** [comment]
I am afraid the only known solution to this problem is to completely delete Thorium's configuration folder, which results in loosing all settings and publications. Naturally, this drastic measure is only recommend as the last resort, when all else fails.

@panaC would it be possible to call `compact()` at application startup, without messing up the application boot process? Also, it would be nice to expose the `compact()` feature via some sort of semi-hidden advanced feature, so that end-users themselves can attempt to call the DB compaction command at any time, rather than just automatically at application launch and exit. Thoughts?

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/thorium-reader/issues/1312

**Comment by danielweck** [comment]
Related: https://github.com/edrlab/thorium-reader/issues/1313

**Comment by danielweck** [comment]
This PR will help alleviate the issue of huge DB growth: https://github.com/edrlab/thorium-reader/pull/1359

**Comment by llemeurfr** [comment]
Version 1.7 will feature a new database. Until then, the current issue cannot be alleviated more than done in #1359, therefore I propose to close it.

**Comment by sukiletxe** [comment]
Will this mean that the current alpha and beta book lists will be incompatible?

**Comment by sukiletxe** [comment]
Oh, thank you!

**Comment by pashaie** [comment]
thanks

**Comment by panaC** [comment]
work in progress in PRs #1415 to #1420
