### ISSUE TITLE
media overlays, issue, Galdo's gift

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1281]
With v1.5 and v1.6 alpha on MacOS Big Sur, the sample of Galdo's Gift plays the background music, but the media overlaid voice does not play.

**Comment by llemeurfr** [comment]
bad manipulation on my side...

**Comment by danielweck** [comment]
This particular fixed layout EPUB3 Media Overlays uses proprietary Apple iBooks extensions to start/stop the synchronised text-audio rendition. Thorium ; or more precisely: `r2-navigator-js` ; implements support for these extensions, and in fact also for the "background audio track" which you mentioned.
There is a noticeable issue when mixing application- vs. content-driven playback: when the Media Overlays is started using the application's own top-level "chrome" (i.e. UI play button in the middle of the reader view toolbar), the content doesn't execute a number of dynamic / interactive features, and playback appears slightly broken (I cannot remember exactly, it's been a while since I last tried). Conversely, when playback is started/paused from the authored user interface, the scripted presentation is executed as per the content creator's intent.
