### ISSUE TITLE
1.6: macOS errors on return from hidden

### ISSUE THREAD

**Issue by raxelbrof** [edrlab/thorium-reader#1388]
Error that occurs after Thorium has been returned to foreground after being hidden by another app (HocusFocus).

macOS 10.13, Thorium 1.6

![image](https://user-images.githubusercontent.com/64583201/108619403-5f5cab80-7470-11eb-828d-05149eea5286.png)

**Comment by danielweck** [comment]
Thank you for reporting this bug.

@panaC I think we need to verify all usages of `getLibraryWindowFromDi()` and `getReaderWindowFromDi()`, because some function calls are not appropriately followed by sanity checks on `null`/`undefined`.
https://github.com/edrlab/thorium-reader/blob/67cada25fba785488d23817413960c79cffafa5c/src/main/di.ts#L275
https://github.com/edrlab/thorium-reader/blob/67cada25fba785488d23817413960c79cffafa5c/src/main/di.ts#L283

As for the `HocusFocus` type of show/hide behaviour, it would be interesting to know exactly what makes the `BrowserWindow` reference become `null`/`undefined` in the Dependency Injection container:

https://github.com/edrlab/thorium-reader/blob/67cada25fba785488d23817413960c79cffafa5c/src/main/di.ts#L270-L273

**Comment by danielweck** [comment]
@panaC I have also noticed inconsistencies in how the functions are called from Saga generator functions, for example:

`const libraryWindow = yield* callTyped(() => getLibraryWindowFromDi());`
https://github.com/edrlab/thorium-reader/blob/67cada25fba785488d23817413960c79cffafa5c/src/main/redux/sagas/win/reader.ts#L84

vs.

`const libraryAppWindow = getLibraryWindowFromDi();`
https://github.com/edrlab/thorium-reader/blob/67cada25fba785488d23817413960c79cffafa5c/src/main/redux/sagas/api/publication/export.ts#L17

Does this matter, or is it just good practice in Redux Saga?

**Comment by raxelbrof** [comment]
FYI along with this error behaviour, the main Thorium window will shift position when returning from hidden, to position itself at the extreme left of the total display space - so on a 3 display system (with a single space / menubar on the centre display), it will move from the centre display, to the far left of the left display (overlapping onto the middle).

**Comment by panaC** [comment]
```
// On OS X it's common to re-create a window in the app when the dock icon is clicked and there are no other
// windows open.
function* appActivate() {

    if (closeProcessLock.isLock) {

        error(filename_ + "appActivate", new Error("closing process not completed"));
    } else {

        const libWinState = yield* selectTyped((state: RootState) => state.win.session.library);

        // if there is no libWin, so must be recreated
        if (libWinState.browserWindowId && libWinState.identifier) {
            const libWin = getLibraryWindowFromDi();

            if (libWin.isMinimized()) {
                libWin.restore();
                libWin.show();
            } else if (libWin.isVisible()) {
                libWin.show();
            } else {

                const readers = yield* selectTyped((state: RootState) => state.win.session.reader);
                const readersArray = ObjectKeys(readers);
                const readerWin = getReaderWindowFromDi(readersArray[0]);

                if (readerWin.isMinimized()) {
                    readerWin.restore();
                }
                readerWin.show();
            }

        } else {

            yield put(winActions.library.openRequest.build());
        }
    }

}
```

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/0923ff2b378d877d93bf83a9c386da615af2f1d6/src/main/redux/sagas/win/browserWindow/createLibraryWindow.ts#L92-L96

https://github.com/edrlab/thorium-reader/search?q=saveLibraryWindowInDi

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/638b62e5fe94965bb413c18554e27ffcd4551973/src/main/redux/reducers/win/session/library.ts#L25-L33

**Comment by panaC** [comment]
this is not clear. It should not happen
Weird race condition !

I continue to investigate , thanks to you

**Comment by panaC** [comment]
" I think we need to verify all usages of getLibraryWindowFromDi() and getReaderWindowFromDi(), because some function calls are not appropriately followed by sanity checks on null/undefined." 

I don't think so. the error message box is made for this case. if we sanity check the getter function and silently bypass the error. How to handle the error without discard it ?
the app state become unstable.

**Comment by danielweck** [comment]
> " I think we need to verify all usages of getLibraryWindowFromDi() and getReaderWindowFromDi(), because some function calls are not appropriately followed by sanity checks on null/undefined."
> 
> I don't think so. the error message box is made for this case. if we sanity check the getter function and silently bypass the error. How to handle the error without discard it ?
> the app state become unstable.
> 
> throws an exception is fair for me. It's a fatal error in this case.

Ah, but this situation is different, because if TypeScript `strictNullChecks` was activated, the compiler would fail where `null` / `undefined` values are not checked appropriately. That's a typical "sniff test" for "code smells" :)

In other words, the contract of these functions is that they *can* indeed return `null` or `undefined` values, so the consuming code should always check for this scenario (even if it means throwing a local exception explicitly to describe the "unexpected error").

**Comment by panaC** [comment]
You're right the exception should throw in the getter instead
