### ISSUE TITLE
Documentation: add missing shortcuts to wiki and update spanish page

### ISSUE THREAD

**Issue by nvdaes** [edrlab/thorium-reader#1392]
Hello: `control+home` and `control+end`aren't not added to the wiki. When this is done, I can update the spanish shortcuts page.

BTW: I have seen some grammar errors in the translation of spanish documentation which is opened by pressing the button More information. Maybe due to automatic translations. I read that I made a mistake in XHTML file, probably when I tried to adjust the length of lines. Maybe you can consider to use markdown and some converter.
Also, for me a good example of managing translations is @NVAccess, which participates in a mailing list for this purpose, informing about string freezes so that translators know when time will finish to include their work in stable releases of NVDA screen reader, which is translated into more than 30 or 40 languages.
What do you thing? It may improve translations quality.

**Comment by danielweck** [comment]
Oh, well spotted, thank you so much for bringing this to my attention.

I added this line:

```
* `CTRL` + `Home` or `End` (`NavigateToBegin` / `NavigateToEnd`): in reader window, goes to the beginning or the end of the publication
```

I placed the above line just before the `CTRL + 1 (AudioPrevious)` line.

**Comment by danielweck** [comment]
Regarding the translations: apologies, there have been changes in the "about Thorium" information, which required replacing existing translations rather than tweaking them. Thorium does not have a process for maintaining translations yet. I created a wiki page to track existing contributors, and you are of course listed so that we can ask for your help in future updates (smile), just in case you are still willing and able to assist:
https://github.com/edrlab/thorium-reader/wiki/Localization-(l10n)-language-translations

@llemeurfr maybe a Slack channel to keep translators informed of changes in the English reference localization JSON, or a GitHub discussion so that people can get notified? Or a more sophisticated solution as discussed in this open issue:
https://github.com/edrlab/thorium-reader/issues/1110

**Comment by nvdaes** [comment]
Thanks Daniel. Here's spanish wiki page updated with your changes. I'll also update the NVDA's spanish website contributed by me and others, where I posted Thorium shortcuts with lang attribute set to Spanish, so it can be properly read, since, as far as I know, GitHub wikis don't have this option:

https://nvdaes.github.io/epub7
[Keyboard-shortcuts-(Spanish).zip](https://github.com/edrlab/thorium-reader/files/6026988/Keyboard-shortcuts-.Spanish.zip)

**Comment by llemeurfr** [comment]
I agree that splitting lines in the XHTML content is a nightmare and that working on markdown first, then transforming it to xhtml via scripts would be a good solution.
