### ISSUE TITLE
[DEV] ln could be undefined

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1398]
https://github.com/edrlab/thorium-reader/blob/15b628a49a941901109cf2c5151828d0dca3b0d1/src/main/converter/opds.ts#L186-L202

**Comment by danielweck** [comment]
For people reading this in the future: the lack of compile-time Typescript check for this obvious coding error is because `strictNullChecks` is not currently enabled in Thorium.

Note that even with `strictNullChecks`, the `!` non-nullish assertion can be used to override this sanity check, but this is obviously very bad practice. See for example:

https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=5&pc=36#code/GYVwdgxgLglg9mABFApgZygCgDZgFyICqASgDKIA+i4AJisDGCjQJSIDeAsAFCJ+IQEaONhQA6bHADmOMAEIxACwBO9FgG4eAXx6oMmWvUbMWu9FiYB3ImUwAiRVCgAHNHgD07mnAC2AQ0YxQR87FhYgA

```
function test(ln: URL | undefined) {
    console.log(ln!.href);
}
test(undefined)
test(new URL("https://domain.com"))
```
