### ISSUE TITLE
[DEV] IOpdsMetada replace with ternary

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1402]
https://github.com/edrlab/thorium-reader/blob/15b628a49a941901109cf2c5151828d0dca3b0d1/src/main/converter/opds.ts#L521-L529

**Comment by danielweck** [comment]
Note that even when fixed (i.e. forbid the production of `boolean` for `numberOfItems`, `itemsPerPage` and `currentPage`) this piece of code can still create an empty object `{}` when `r2OpdsFeed.Metadata` is not `undefined`/`null`, and when neither `NumberOfItems` nor `ItemsPerPage` nor `CurrentPage` are not `undefined`/`null`.

Here is a repro sample (using `strictNullChecks` for good practice, even though this is not currently enabled in Thorium's codebase):

https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=19&pc=1#code/CYUwxgNghgTiAEAXAngBwQSQPKuAZwDEQRgBZERKYKS+AXngG94A5AVwFsAjEGLAMwyIQHPAC54AO048Y8AD7w2k0PwCWkkgBp4QkXgAKvA1ADmICdO68FSlSHWbgOgMJsYcSYhPnLMm4rKqhok8AC+ALAAUNGgkLAIKOi6OPhEJOSU1JQAamogAO70TFL+fILCon7WcoH2jtrwapWGxmYWpTW2QQ4hzvBg7p7e7dWy3fV94dGx4NBw8BAU8DAATKmExMASjNHw+-CZVDRQEti4mxkUx7R1wU7RkTFRYAD2kniI8BzX2acpF3SZF+JzyhQm91CDDWGyBADojn94AB+aK7KIHTqyAR6KpINAgV78FbrQFbBEgyhw9g1HEteh0BgAIissiZKL2mIOMLJJApWRO1LKdP08AkPQazk5+2a+iMMB8HSShOJPLS5MRgtxrQV7QZzNZvHZqIxXP2asuwH5NygcO18sVYrskKlpv2gw8IC8iokyqJJNhGsptrcnu9esZBrKxulXIt8M1VNDw0d4smTi0jydEr6MyiQA

```
declare type IOpdsFeedMetadata = { NumberOfItems: number | undefined, ItemsPerPage: number | undefined, CurrentPage: number | undefined }

declare type IOpdsFeedMetadataView = { numberOfItems: number | undefined, itemsPerPage: number | undefined, currentPage: number | undefined }

declare let r2OpdsFeed: {
    Metadata: IOpdsFeedMetadata | undefined
}

const metadata: IOpdsFeedMetadataView | undefined = r2OpdsFeed.Metadata ?
{
    numberOfItems: typeof r2OpdsFeed.Metadata.NumberOfItems === "number" ?
        r2OpdsFeed.Metadata.NumberOfItems : undefined,
    itemsPerPage: typeof r2OpdsFeed.Metadata.ItemsPerPage === "number" ?
        r2OpdsFeed.Metadata.ItemsPerPage : undefined,
    currentPage: typeof r2OpdsFeed.Metadata.CurrentPage === "number" ?
        r2OpdsFeed.Metadata.CurrentPage : undefined,
} : undefined
```

**Comment by danielweck** [comment]
For clarity / terseness, let's use the optional `?` operator instead of `| undefined` (which is equivalent with `strictNullChecks`), and let's remove the explicit type of `metadata` (can be inferred):

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAXAngBwQSQPKuAZwDEQRgBZERKYKS+AXngG94A5AVwFsAjEGLAMwyIQHPAH4AXPAB2nHjAA08ISLwAFXmqgBzEJJlzeSgMJsYcaYi279s7r3gBfALAAoN6EiwEKdMpz4RCTklNSUAGoAliAA7vRMBvZ8gsKitoaK8JGp6po6elJ28kpgZhZW+elJTm4e4NBw8BAU8DAATAGExMBSjG7wA-AhVDRQ+ti4XcEUI5RuLu6uYAD20niI8BwzYVDx7Z1BwAB0wzvwYm59roOJ8gIqolK+IMv8rR2Thyfbo0fsSfccvQ6AwAERFXig879G6DfafbrfUK-f53FKqeBSNjSUD8SLSEgKGEDbKqDQwawgJ5oF5veGBRGnX4PXIU-LAsEQmBQi7XWEDelTY5MyhHFnkymY+DY3H4wnE+ClcwgSyU6noV7vA6Mn6i0zK1XskGcjI8hU3QVfEVQI768qSrE4kB4gnAImuRxSmXOuXANxAA

```
declare type IOpdsFeedMetadata = { NumberOfItems?: number, ItemsPerPage?: number, CurrentPage?: number }

declare type IOpdsFeedMetadataView = { numberOfItems?: number, itemsPerPage?: number, currentPage?: number }

declare let r2OpdsFeed: {
    Metadata?: IOpdsFeedMetadata
}

const metadata: IOpdsFeedMetadataView | undefined = r2OpdsFeed.Metadata ?
{
    numberOfItems: typeof r2OpdsFeed.Metadata.NumberOfItems === "number" ?
        r2OpdsFeed.Metadata.NumberOfItems : undefined,
    itemsPerPage: typeof r2OpdsFeed.Metadata.ItemsPerPage === "number" ?
        r2OpdsFeed.Metadata.ItemsPerPage : undefined,
    currentPage: typeof r2OpdsFeed.Metadata.CurrentPage === "number" ?
        r2OpdsFeed.Metadata.CurrentPage : undefined,
} : undefined
```

**Comment by danielweck** [comment]
Note that the removal of the explicit type of `metadata` is dangerous, for example if by mistake the `??` operator is used instead of the more verbose ternary. Note that the inferred type is totally incorrect in the context of this code snippet:

```
const metadata: {
    numberOfItems: boolean;
    itemsPerPage: boolean;
    currentPage: boolean;
} | undefined
```

https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=18&pc=1#code/CYUwxgNghgTiAEAXAngBwQSQPKuAZwDEQRgBZERKYKS+AXngG94A5AVwFsAjEGLAMwyIQHPAH4AXPAB2nHjAA08ISLwAFXmqgBzEJJlzeSgMJsYcaYi279s7r3gBfALAAoN6EiwEKdMpz4RCTklNSUAGoAliAA7vRMBvZ8gsKitoaK8JGp6po6elJ28kpgZhZW+elJTm4e4NBw8BAU8DAATAGExMBSjG7wA-AhVDRQ+ti4XcEUI5RuLu6uYAD20niI8BwzYVDx7Z1BwAB0wzvwYm59roOJ8gIqolK+IMv8rR2Thyfbo0fsSfccvQ6AwAERFXig84Xa43Qb7T7db6hX7-O4pVQKfqDbKqDQwawgJ5oF5vBGBJGnX4PXIE-LAsEQmBQsQwuHwj4UkjI2ZQI40-GErGwgalcwgSyE4noV7vA6Un6UI6mcWS+kgxkZFls9lyxHcqlKlXlIXzeBSNjSUD8SLSEhuIA

```
declare type IOpdsFeedMetadata = { NumberOfItems?: number, ItemsPerPage?: number, CurrentPage?: number }

declare type IOpdsFeedMetadataView = { numberOfItems?: number, itemsPerPage?: number, currentPage?: number }

declare let r2OpdsFeed: {
    Metadata?: IOpdsFeedMetadata
}

const metadata = r2OpdsFeed.Metadata ?
{
    numberOfItems: typeof r2OpdsFeed.Metadata.NumberOfItems === "number" ??
        r2OpdsFeed.Metadata.NumberOfItems,
    itemsPerPage: typeof r2OpdsFeed.Metadata.ItemsPerPage === "number" ??
        r2OpdsFeed.Metadata.ItemsPerPage,
    currentPage: typeof r2OpdsFeed.Metadata.CurrentPage === "number" ??
        r2OpdsFeed.Metadata.CurrentPage,
} : undefined
```
