### ISSUE TITLE
Pagination - scrolling problems

### ISSUE THREAD

**Issue by dolevu** [edrlab/thorium-reader#1524]
1. You have to mouse hover the scroll bar at the bottom to get mouse scroll / 2 finger touchpad work.
It should work without the mouse hover requirement.

2. Expected behavior: Scroll down --> next page. Scroll up --> previous page. 
Right now it works oppositely.

**Comment by llemeurfr** [comment]
Thanks for the message. This feature is still experimental, as Thorium pagination was initially meant to be driven by the keyboard + mouse clics on dedicated buttons. 

 We will first correct the "Right now it works oppositely" issue (which will be ok both for natural yes/no mode). 
 
 Having automatic page turn work when the mouse ove over the bottom of a page, outside the bottom area in more complex, we'll see this later.

**Comment by llemeurfr** [comment]
See also #1436

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/129904b244044a61dd6db25bc6e178bf1795cdb8
("natural" touchpad flick/swipe gesture scrolling direction)

The other issue is tracked here: https://github.com/edrlab/thorium-reader/issues/1436
(touch/mouse scroll on the entire paginated document / rendered HTML, instead of just the bottom bar)
