### ISSUE TITLE
Problem with accessing state from a new module

### ISSUE THREAD

**Issue by FirstyGroup** [edrlab/thorium-reader#1698]
Hi everyone, I am having a bit of a trouble with accessing the global state, most likely I am simply missing something obvious, hopefully someone will be able to spot the problem

The distilled version of the problem:

Step 1. Fresh clone of Thorium
git clone -b develop https://github.com/edrlab/thorium-reader.git

npm install, etc.

Step 2. The logger has been added to see the redux state in the terminal, the Thorium compiles and runs fine at this stage

Step 3. The "Settings" component has been duplicated in the renderer/library/components, just a copy paste and with the edits to these files to make the links work:

src/renderer/library/routing.ts
src/renderer/library/components/layout/LibraryHeader.tsx
src/resources/locales/en.json

Step 4. The session module, the one which handles the "Save session" control has been cloned as Indigo, I think nothing has been missed at this stage, the app compiles and runs fine

1.  src/renderer/library/components/glassboxxLogin/IndigoSettings.tsx
2.  src/resources/locales/en.json
3.  en.translation.d.ts
4.  src/common/api/interface/indigo.interface.ts
5.  src/common/api/interface/api.type.ts
6.  src/common/api/interface/methodApi.type.ts
7.  src/common/api/interface/moduleApi.type.ts
8.  src/main/api/indigo.ts
9.  src/main/di.ts
10. src/main/diSymbolTable.ts
11. src/main/redux/states/indigo.ts
12. src/main/redux/states/index.ts
13. src/main/redux/reducers/indigo.ts
14. src/main/redux/reducers/index.ts
15. src/main/redux/actions/index.ts
16. src/main/redux/actions/indigo
17. src/main/redux/middleware/persistence.ts
18. src/main/redux/sagas/persist.ts

Step 4. A couple of test controls added to the module, with the necessary changes throughout the files - again, all working fine, the state changes can be clearly seen via the logger

The screenshots show the new module, the state changes visible via the redux logger and the state visible from the React component

<img width="855" alt="Screenshot 2022-05-30 at 13 21 45" src="https://user-images.githubusercontent.com/12299040/170995425-ee96a77c-6fdc-4839-8522-074f2fdb356d.png">
<img width="632" alt="Screenshot 2022-05-30 at 13 45 29" src="https://user-images.githubusercontent.com/12299040/170995429-5f8076ee-4b66-4a73-92dd-ac50e0171a66.png">
<img width="675" alt="Screenshot 2022-05-30 at 13 45 56" src="https://user-images.githubusercontent.com/12299040/170995434-f5b8fcf9-1254-486b-89e9-1af3ab0602f2.png">

Step 5. What is needed at this point is the visibility of new "indigo" state to React and this is where all started to go downhill.

To make the state visible I've tried to add it to the ICommonRootState
src/common/redux/states/renderer/commonRootState.ts

This alone is not enough, there are compiler errors about the reducers, the new reducers should be included in
src/renderer/library/redux/reducers/index.ts
src/renderer/reader/redux/reducers/index.ts

At this point the normal syntax errors disappear and instead there is this one:

<img width="937" alt="Screenshot 2022-05-30 at 14 01 01" src="https://user-images.githubusercontent.com/12299040/170997923-ef19f98e-98f4-4f0c-aea9-a759abb56c27.png">

Not knowing what to make of this I've tried first to delete the node_modues directory and reinstall npm, that did not make any difference.

I've also tried to comment out the references to lunr, it was not difficult to disable it altogether but it did not help, the app just started to launch with the blank screen

Additional details can be provided if that would help but this is the essence of the problem, can anyone spot any flaws in the steps above?

Dennis

**Comment by panaC** [comment]
Hello.

It's seems you imported a file from the main directory to the renderer directory.
Perhaps `src/renderer/reader/redux/reducers/index.ts`

Which is the contents of this file ?

**Comment by danielweck** [comment]
Hello, if I remember correctly, `lunr` is not used actively anymore in Thorium 2.0 (the library search feature now handles text matches completely differently, via the new bookshelf table / data grid view).
However I see some "left over" files so we will need to check whether or not they are necessary, ASAP (so that the codebase can be cleaned up):
https://github.com/edrlab/thorium-reader/blob/03b16f62c25351d7f0ffcb9281f28d58d0b46474/src/main/db/repository/publication.ts#L21-L24
https://github.com/edrlab/thorium-reader/blob/03b16f62c25351d7f0ffcb9281f28d58d0b46474/package.json#L257-L258

The most significant "under the hood" change in Thorium 2.0 is the complete removal of LevelDown (prod) and SQLite3 (dev) PouchDB adapters. This move started several releases ago "behind the scenes", by only accessing the persistent DB storage in read mode, and by writing to a new JSON on-disc format. At this present time, many months after the start of the deprecation of native database backends, we expect everybody to have used Thorium releases that have successfully (and silently) migrated user data into the new JSON backend. Thus the complete removal of native DB "read" (elimination of the now-unnecessary package dependencies).

So, in your upgrade to v2.0, it will be interesting to see if existing / installed Firsty apps will be able to seamlessly operate based on the already-migrated user data (i.e. bookshelf publications, settings, etc.).

**Comment by FirstyGroup** [comment]
@danielweck While lunr module may or may not be relevant anymore it is a bit strange that attempt to adde a new state triggers an error in seemingly unrelated bit of code

As for the old/new version of Thorium we will provide a feedback on how the upgrades go, in our case there will be a rather large gap between the versions

**Comment by danielweck** [comment]
UPDATE: `lunr` is in fact needed by the CLI feature "find by title / author" :)

**Comment by danielweck** [comment]
> As for the old/new version of Thorium we will provide a feedback on how the upgrades go, in our case there will be a rather large gap between the versions

If you experience data upgrade problems (typically: empty bookshelf and/or lost settings) when testing your fork based on Thorium 2.0, then this is a clear indication that you will need to offer an upgrade path, like we did in Thorium. You will have to first build and deploy a fork based on Thorium 1.8, and give your userbase some time (the read-only native DB will be migrated to JSON persistence). Once you are confident about the transition in the vast majority / entirety of your userbase, then a Thorium 2.0 fork deployment should be pain-free (seamless) for your users.

**Comment by FirstyGroup** [comment]
@panaC I see now, the wrong process, should have paid attention to it, my mistake. Thank you for pointing it out!
