### ISSUE TITLE
Localisation of the presentation of the software on the Windows Store

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1868]
When looking at usage stats for downloads from the Windows Store, it appears the most users are from Canada, France, the USA, Japan and Spain. With 18 localisation languages, we thing there is something to do to foster the use of Thorium is other countries (and therefore make sure translations are useful). 

The presentation of Thorium on the Windows Store is currently in English and French only. I have written an update of this presentation in English and French, and would be happy if you, wha are helping us maintaining label translations, could translate the text below IN THIS GITHUB ISSUE, in your native language. We'll then integrate it on the Windows Store for the next version. 

--- EN
Thorium Reader is a free, highly accessible, multilingual and multi-format reading application. It has a modern user interface with no ads or private data leakage.
This application is one of the best EPUB 3 readers on the market; you can also read PDF or DAISY files and listen to audio books.
Thorium Reader supports Readium LCP DRM-protected publications borrowed from public libraries or purchased from booksellers' websites.
This open-source project from the European Digital Reading Lab is constantly evolving: please help with its development at https://github.com/sponsors/edrlab. And don't forget to leave a review on this site! 

Functionalities:

Supports EPUB 2, EPUB 3, PDF, DAISY, LPF formats.
Allows you to easily manage your library of books and audio books.
Allows you to navigate through books and audiobooks by their table of contents.
Allows you to read in paginated or scrolled mode.
Has sepia and night themes.
Allows you to finely modify the presentation of texts.
Allows you to zoom in on the images contained in EPUBs.
Allows you to read the text aloud.
Manages EPUBs associated with an audio track.
Provides full-text search capabilities.
Allows bookmarks to be placed in the text and bookmarks to be named.
Supports LCP DRM.
Compatible with NVDA and JAWS screen readers.
Supports MathML.
Provides access to OPDS-formatted book catalogs.
Interfaces with your Calibre library via its OPDS feed.
Allows you to classify your books via personal labels.

---

**Comment by gautierchomel** [comment]
Hi, known translators @horus68 @milliet @martinpub @Modeo147 @naglis @jacoporinaldi @peaceroad @panaC @nvdaes @HadrienGardeur @tofi86 @terhol-celia @maitreya2019 @cary-rowen @ThanatosDi @georgegach @sukiletxe, could you help with localizing this short text? 

Proposed process is to paste translation here as comment to this issue.

**Comment by ThanatosDi** [comment]
--- zh-tw
Thorium Reader 是一款免費、易於訪問、多語言和多格式的閱讀應用程序。它有一個現代的使用者界面，沒有廣告或個人數據洩漏。
此應用程式是市場上最好的 EPUB 3 閱讀器之一；您還可以閱讀 PDF 或 DAISY 文件並收聽有聲讀物。
Thorium Reader 支援從公共圖書館借用或從書商網站購買的受 Readium LCP DRM 保護的出版物。
這個來自歐洲數字閱讀實驗室的開源項目在不斷發展：請訪問 https://github.com/sponsors/edrlab 幫助其開發。並且不要忘記在此網站上留下評論！

功能：

支援 EPUB 2、EPUB 3、PDF、DAISY、LPF 格式。
讓您輕鬆管理您的圖書和有聲讀物庫。
可讓您按目錄瀏覽書籍和有聲讀物。
可讓您以分頁或滾動模式閱讀。
有棕褐色和夜間主題。
可讓您精細修改內容文字的顯示。
可讓您放大 EPUB 中的圖片。
可讓您大聲朗讀文本。
管理與音軌關聯的 EPUB。
提供全文搜索功能。
允許將書籤放置在文本中，並允許書籤被命名。
支援 LCP DRM。
與 NVDA 和 JAWS 螢幕閱讀器兼容。
支援 MathML。
提供對 OPDS 格式的圖書目錄訪問。
通過其 OPDS feed 與您的 Calibre 圖書館互動。
可讓您通過個人標籤對書籍進行分類。

**Comment by martinpub** [comment]
--- sv
Thorium Reader är ett fritt läsprogram med hög grad av tillgänglighet och stöd för ett antal olika språk och format. Programmet har ett modernt användargränssnitt, läcker inga privata data och är fritt från reklam. Det här är ett av de bästa läsprogrammen för EPUB 3 på marknaden och du kan också läsa PDF- eller DAISY-filer och lyssna på ljudböcker.

Thorium Reader har stöd för Readium LCP DRM-skyddade publikationer som lånas via bibliotek eller köps hos nätbokhandlar. Programmet är ett öppen källkod-projekt från European Digital Reading Lab och utvecklas löpande. Stöd gärna utvecklingen av programmet via https://github.com/sponsors/edrlab. Och glöm inte att lämna en recension på den här sidan!

Funktionalitet:

Stöd för formaten EPUB 2, EPUB 3, PDF, DAISY och LPF.
Du kan lätt administrera ditt bibliotek av böcker och ljudböcker.
Du kan navigera genom böcker och ljudböcker med deras innehållsförteckning.
Du kan läsa i sidindelat läge eller scroll-läge.
Sepia- och nattläge.
Du kan styra i detalj hur texten presenteras.
Du kan zooma in på bilder som ingår i EPUB-böcker.
Du kan få texten uppläst.
Hanterar EPUB-böcker med ljudspår.
Har funktionalitet för sökning i fulltext.
Möjlighet att sätta bokmärken i texten och döpa dem.
Stöd för LCP DRM.
Kompatibel med skärmläsarna NVDA och JAWS.
Stöd för MathML.
Tillgång till bokkataloger via OPDS.
Kan kopplas ihop med ditt Calibre-bibliotek via dess OPDS-flöde.
Du kan tagga dina böcker med egna taggar.

**Comment by nvdaes** [comment]
Es

Thorium Reader es una aplicación de lectura, gratuita, muy accesible, que admite múltiples idiomas y formatos. Tiene una interfaz de usuario moderna, sin anuncios ni datos privados compartidos. Esta aplicación es uno de los mejores sistemas para la lectura de EPUB 3 del mercado; también puedes leer ficheros PDF o DAISY y escuchar audiolibros.
Thorium Reader admite publicaciones protegidas mediante DRM Readium LCP, prestadas desde bibliotecas públicas o compradas en librerías disponibles en sitios web.
Este proyecto de código abierto de European Digital Reading Lab está en constante evolución. Por favor, ayuda a su desarrollo en
https://github.com/sponsors/edrlab. ¡Y no olvides dejar una revisión en esta web!

Funcionalidades

Admite los formatos EPUB 2, EPUB 3, PDF, DAISY, LPF.
Te permite gestionar fácilmente tu biblioteca de libros y audiolibros.
Te permite navegar por los libros y audiolibros mediante su tabla de contenido.
Te permite leer en modo paginado o desplazable.
Dispone de diseños sepia y noche.
Te permite modificar de forma precisa la presentación de los textos.
Te permite ampliar las imágenes incluidas en los EPUB.
Te permite leer el texto en voz alta.
Gestiona los EPUB asociados a una pista de audio.
Proporciona funcionalidad completa para la búsqueda de texto.
Permite colocar marcadores en el texto y nombrar los marcadores.
Admite el DRM LCP.
Compatible con los lectores de pantalla NVDA y JAWS.
Admite MathML.
Proporciona acceso a catálogos de libros en formato OPDS.
Interactúa con tu biblioteca Calibre a través de su fuente OPDS.
Te permite clasificar tus libros mediante etiquetas personalizadas.

**Comment by jacoporinaldi** [comment]
-- IT - Italian

Thorium Reader è un'applicazione di lettura gratuita, altamente accessibile, multilingua e multi-formato. Ha un'interfaccia moderna, senza pubblicità e fuga di dati privati.
L'applicazione è uno dei migliori reader di EPUB 3 sul mercato; è anche possibile leggere files PDF o DAISY ed ascoltare audiolibri.
Thorium Reader supporta le pubblicazioni protette dal DRM Readium LCP prese in prestito da librerie pubbliche o acquistate da rivenditori digitali.
Il progetto open-source sviluppato da Euopean Digital Reading Lab è in costante evoluzione: per favore, aiuta lo sviluppo a https://github.com/sponsors/edrlab. E non dimenticare di lasciare una recensione su questo sito!

Funzionalità:

Supporta formati EPUB 2, EPUB 3, PDF, DAISY ed LPF.
Permette di gestire facilmente la tua libreria di libri ed audiolibri.
Permette di navigare attraverso libri ed audiolibri attraverso il loro indice/tabella dei contenuti.
Permette di leggere in modalità scroll o impaginata.
Sono presenti i temi Seppia e Notte.
Permette di modificare con accuratezza la presentazione dei test.
Permette di zoommare sulle immagini contenuti negli EPUBs.
Permette la lettura del testo con il lettore a voce alta.
Gestisce EPUBs associati con una traccia audio.
Fornisce la funzionalità di ricerca nel testo.
Permette il piazzamento di segnalibri all'interno del testo e la possibilità di rinominarli a piacimento.
Supporta il DRM LCP.
Compatibile con i lettori di schermo NVDA e JAWS.
Supporta MathML.
Fornisce accesso a cataloghi di libri in formato OPDS.
Permette di classificare i tuoi libri attraverso etichette personali.

A quick question to @llemeurfr : "Allows to finely modify the presentation of texts": is modify exactly what you mean, or is it customize? On the first case the translation above is correct. Otherwise the string "Permette di modificare con accuratezza la presentazione dei test" needs to be changed into "Permette di personalizzare con accuratezza la presentazione dei test."

That is all for the italian translation.

**Comment by nvdaes** [comment]
Hello:

After reading [comment by @Adecabo9](https://github.com/edrlab/thorium-reader/issues/1868#issuecomment-1319966599), I'd like to mention some differences between spanish translations, remarking that some expressions, though different, seem to be valid in both cases.

- I placed a comma between the word "lectura" (reading) and "free" (gratuita), to make easy to understand that free is related to Thorium, that is, we may read books that aren't free, so it's not a free reading (lectura gratuita without comma).
- I've translated "scrolled" as "desplazable" (name of one of the available modes) instead of "desplazado" since scrolling is something that can be done, and the movement is not done as a predefined action. It's something possible, not intrinsic.
- I have used "ni datos privados compartidos" instead of "sin pérdida de datos privados" since leak, imo implies something going out, and missing (pérdida) may happen if for example data is deleted. For me is less confusing to point out the meaning of leak as something that can go out the application and that in this case won't happen.
- I've used "etiquetas pesonalizadas" since personal maybe translated as "personalizado" and personal can mean also something private, while "personalizado" is used for example when we create commands in a toolbar for a program, so I think that thiw word is more precise for this context.
- About search, I have translated the corresponding fragment as "Proporciona funcionalidad completa para la búsqueda de texto", since full is not related to text, imo. It's mentioning the search functionality. In fact text may not be complete and even we can search pieces of a word.
- I haven't translated the name of European Reading Laboratory, since it's the name of an organization and some organizations are named "Lab" in Spanish and this is not translated, at least in Spain, my country.

These are clarifications in case we can reach a common translation or if one of them has to be chose.
Kind regards.

**Comment by maitreya2019** [comment]
--zh-cn

Thorium Reader 是一款免费、易于访问、提供多语言和多格式支持的阅读软件。它拥有现代风格的用户界面，无广告植入或隐私数据泄漏之虞。
本软件是市面上最优秀的 EPUB 3 阅读器之一；您也可以用它阅读 PDF 或 DAISY 文件并收听有声读物。
Thorium Reader 支持从公共图书馆借阅或从书商网站购买的受 Readium LCP 数字版权管理（DRM）保护的出版物。
这一来自欧洲数字阅读实验室的开源项目目前正处于持续开发过程中：请访问 https://github.com/sponsors/edrlab 为我们助力。并且不要忘记在此页面留下评论！

功能：

支持 EPUB 2、EPUB 3、PDF、DAISY、LPF 等电子书格式。
可让您轻松管理您的电子书和有声读物库。
可让您按目录浏览电子书和有声读物。
可让您以分页或滚动模式进行阅读。
拥有茶色及夜间主题。
可让您精细修改文字内容的显示方式。
可让您放大 EPUB 电子书中的图片。
可让您大声播放文本语音。
管理与音轨关联的 EPUB 电子书。
提供全文检索功能。
可在文本中插入书签，并为书签命名。
支持 LCP 数字版权管理（DRM）。
与 NVDA 和 JAWS 屏幕阅读器兼容。
支持 MathML。
提供对 OPDS 格式书库目录的访问。
通过 OPDS 订阅与您的 Calibre 书库交互。
可让您通过个人标签对图书进行分类。

**Comment by peaceroad** [comment]
I realized it late.
If you have time, please do so below.

--- JA
Thorium Readerは無料であり、高機能のアクセシビリティ、多くの表示言語・ファイル形式に対応した読書アプリケーションです。広告は表示されず、個人データの漏洩がないモダンなユーザーインターフェイスを備えています。
このアプリケーションは、マーケットにおける最高のEPUB 3リーダーの1つです。PDFやDAISYファイルを読んだり、オーディオブックを聴いたりすることもできます。
Thorium Readerは、公立図書館から借りたり、書店のウェブサイトから購入したりした、Readium LCP DRMで保護された出版物に対応しています。
このオープンソースプロジェクトはEuropean Digital Reading Labによって継続して開発されています。その開発について https://github.com/sponsors/edrlab で協力してください。そして、このサイトでレビューを残すことを忘れないでください！

機能：

フォーマットはEPUB 2、EPUB 3、PDF、DAISY、LPFに対応。
本やオーディオブックのライブラリー（本棚）を簡単に管理できる。
本やオーディオブックの目次を通して読みたい箇所まで移動できる。
表示形式としてページ型またはスクロール型を選択して読める。
表示テーマに、セピアと夜間もある。
テキストの表示を細かく変更できる。
EPUB書籍内の画像を拡大できる。
テキストを読み上げることができる。
オーディオトラックに関連付けられたEPUBを管理できる。
全文検索機能がある。
書籍内のテキストにブックマークすることができ、それに名前を付けられる。
LCP DRMに対応。
スクリーンリーダーであるNVDAおよびJAWSと互換性がある。
MathMLに対応。
OPDS形式の図書目録へのアクセスを提供する。
OPDSフィード経由で、手元のCalibreライブラリーと連携できる。
自分でラベルを付けて、本を分類できる。

**Comment by tofi86** [comment]
--de

Thorium Reader ist eine kostenlose, leicht zugängliche, mehrsprachige und mehrformatige Leseanwendung. Sie verfügt über eine moderne Benutzeroberfläche ohne Werbung oder Weitergabe privater Daten.
Diese Anwendung ist einer der besten EPUB 3-Reader auf dem Markt. Sie können auch PDF- oder DAISY-Dateien lesen und Hörbücher anhören.
Thorium Reader unterstützt mit "Readium LCP" DRM-geschützte Publikationen, die Sie in öffentlichen Bibliotheken ausgeliehen oder auf den Websites von Buchhändlern gekauft haben.
Dieses Open-Source-Projekt des "European Digital Reading Lab" wird ständig weiterentwickelt: Bitte helfen Sie bei seiner Entwicklung unter https://github.com/sponsors/edrlab. Und vergessen Sie nicht, eine Bewertung auf dieser Seite zu hinterlassen!

Funktionalitäten:

- Unterstützt die Formate EPUB 2, EPUB 3, PDF, DAISY, LPF.
- Ermöglicht Ihnen die einfache Verwaltung Ihrer Buch- und Hörbuchbibliothek.
- Ermöglicht Ihnen die Navigation durch Bücher und Hörbücher anhand ihres Inhaltsverzeichnisses.
- Ermöglicht das Lesen in einem Seitenbasierten- oder im Scrollmodus.
- Verfügt über Sepia- und Nacht-Farbschemas.
- Ermöglicht es Ihnen, die Darstellung von Texten feingranular zu modifizieren.
- Ermöglicht es Ihnen, die in EPUBs enthaltenen Bilder zu vergrößern.
- Ermöglicht es Ihnen, den Text vom System laut vorlesen zu lassen.
- Unterstützt EPUBs, die den Text mit einer hinterlegten Tonspur verknüpft haben.
- Ermöglicht eine Volltextsuche.
- Ermöglicht das Setzen von Lesezeichen im Text und die Benennung von Lesezeichen.
- Unterstützt den "LCP"-Kopierschutz ("DRM").
- Kompatibel mit "NVDA" und "JAWS"-Bildschirmlesern.
- Unterstützung mathematischer Formeln mit "MathML". 
- Ermöglicht den Zugriff auf OPDS-formatierte Buchkataloge.
- Schnittstelle zu Ihrer Calibre-Bibliothek über deren OPDS-Feed.
- Ermöglicht Ihnen die Klassifizierung Ihrer Bücher über persönliche Tags.

**Comment by milliet** [comment]
--pt-br

O Thorium Reader é um aplicativo de leitura gratuito e acessível, que
admite vários idiomas e formatos. Possui uma interface de usuário moderna,
sem anúncios ou compartilhamento de dados privados. Este aplicativo é um
dos melhores sistemas do mercado para a leitura de EPUB 3. Você também pode
ler arquivos PDF ou Daisy e ouvir audiolivros.
O Thorium Reader suporta publicações protegidas pelo DRM Readium LCP,
oferecido por bibliotecas públicas ou compradas em livrarias online.
Este projeto de código aberto, do Laboratório Europeu de Leitura Digital -
EDRLab -, está em constante evolução. Por favor, ajude seu desenvolvimento
em https://github.com/sponsors/edrlab. E não esqueça de deixar um
comentário neste site!

Funcionalidades:

   - Suporta os formatos Epub 2, Epub 3, PDF, Daisy, LPF.
   - Permite gerenciar facilmente sua biblioteca de livros e audiolivros.
   - Permite navegação pelos livros e audiolivros por meio do índice ou
   tabela de conteúdo.
   - Permite que você leia em modo paginado ou escroleável.
   - Oferece temas de fundo em sépia e noturno.
   - Permite modificar com precisão vários aspectos da apresentação dos
   textos.
   - Permite ampliar as imagens incluídas no EPUB.
   - Permite ler o texto em voz alta.
   - Gerencia os epubs associados a uma faixa de áudio.
   - Oferece funcionalidade completa para pesquisa de texto.
   - Permite inserir marcadores no texto e nomeá-los.
   - Admite o DRM LCP.
   - Compatível com os leitores de tela NVDA e JAWS.
   - Suporta MathML.
   - Oferece acesso aos catálogos de livros em formato OPDS.
   - Interage com sua biblioteca Calibre através do uso da sua origem OPDS.
   - Permite categorizar seus livros através de etiquetas personalizadas.



---------------------------------------------------------------------------------------------------

*Pedro Milliet*

 +55 11 98089-9000

***@***.*** ***@***.***>
fenixeditorial.com.br
Praça Amadeu Amaral, 27 - 7º andar - Bela Vista
São Paulo - SP - Brasil - 01327-010

<https://g.page/fenixeditorial?share>
Editorial Services and Solutions
Accessibility and Information Architecture
EDRLab - Member
DAISY Consortium Friend (Inclusive Publisher)
Member of the DAISY Consortium Training and Support Team
ABC (Accessible Books Consortium) Accessibility Collaborator
UNICEF Universal Design Project Consultant
Skype: connatus

Aviso Legal: Esta mensagem e arquivo(s) podem conter informações
confidenciais e/ou legalmente protegidas. Caso tenha recebido por engano,
favor devolvê-la ao remetente e eliminá-la de seu sistema, não utilizando
ou divulgando parte ou a totalidade desta mensagem ou do(s) documento(s) a
ela anexado(s).


Em seg., 21 de nov. de 2022 às 13:57, Tobias Fischer <
***@***.***> escreveu:

**Comment by danielweck** [comment]
Let's close this issue now that the translations are being integrated into the Microsoft Windows Store "submission".
This discussion thread is of course preserved in the project's historical records.

**Comment by horus68** [comment]
pt-PT translation:

O Thorium Reader é um software de leitura gratuito e acessível, multilingue e multiformato. Possui uma interface de utilizador moderna, sem anúncios ou divulgação de dados privados. Este programa é um dos melhores leitores de EPUB 3 existentes e também permite ler ficheiros PDF ou Daisy e ouvir audiolivros. 
O Thorium Reader suporta documentos protegidos por DRM Readium LCP disponibilizados por bibliotecas públicas ou adquiridos em livrarias digitais. É um projeto de código aberto, do Laboratório Europeu de Leitura Digital - EDRLab -, e está em constante evolução. Por favor, ajude ao seu desenvolvimento em https://github.com/sponsors/edrlab. 
E não se esqueça de deixar um comentário neste sítio!

 Funcionalidades: 
- Suporte aos formatos Epub 2, Epub 3, PDF, Daisy, LPF.
- Gestão fácil da sua biblioteca de livros e audiolivros.
- Navegação pelos livros e audiolivros por meio do seu índice. 
- Leitura em modo paginado ou rolável.
- Utilização de temas de fundo em sépia e noturno. 
- Modificação detalhada de vários aspetos da apresentação dos textos. 
- Ampliação das imagens incluídas no EPUB.
- Leitura de texto em voz alta. 
- Gestão de Epub associados a uma faixa de áudio. 
- Funcionalidade completa a pesquisa de texto. 
- Colocação de marcadores personalizados no texto.
- Suporte ao DRM LCP.
- Compatibilidade com leitores de ecrã NVDA e JAWS.
- Suporte a MathML. 
- Acesso via OPDS a catálogos de livros. 
- Interação a bibliotecas Calibre através de sinal OPDS. 
- Categorização de livros através de etiquetas personalizadas.
