### ISSUE TITLE
Bad display for ReadAloud menu in Fr

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1874]
French UI has a bad display for Readaloud options menu. Text is too big and that makes the checkbox displayed alone on one line. 

![Screenshot showing french readaloud menu with a checkbox alone on one line](https://user-images.githubusercontent.com/107039498/202748992-cbf54b69-2700-45c1-bf06-4c7e2c5a1a45.png)

**Comment by gautierchomel** [comment]
This happens also in Display menu : 
![image](https://user-images.githubusercontent.com/107039498/202750105-be35bdfa-1568-4a5f-8b79-5f0cf7ae4d15.png)

**Comment by gautierchomel** [comment]
Lines with checkboxes should have same text size as other options (here Colonnes) and be justified left.
![Screenshot showing french display menu the MathJax checkbox option much bigger than the Column option](https://user-images.githubusercontent.com/107039498/202750403-9fbf1672-13b9-443f-8d14-7033f3dbdb50.png)

**Comment by danielweck** [comment]
Thank you for filing this bug Gautier. The style cascade is quite hard to modify due to side-effects, but I've managed to fix the problem without causing regressions:
https://github.com/edrlab/thorium-reader/commit/9967b6bcf813a66984dc163c63692150ce791482
(I've also fixed the lack of visual feedback for disabled menu items ... again, a bug caused by badly considered CSS selector specificity and nested classes + nested elements)
