### ISSUE TITLE
Dark mode for pdf

### ISSUE THREAD

**Issue by Nriver** [edrlab/thorium-reader#1879]
Dark mode works well for epub. But I noticed the dark mode/night theme does not work in pdf files for now. Could it be supported?

**Comment by danielweck** [comment]
Hello, much like with EPUB Fixed-Layout (FXL) / pre-paginated documents, publisher styles take precedence over user preferences when rendering PDF files. These "pixel perfect" formats are all about respecting authored layout / format / typeset / colour scheme. There is a strong case for accessibility when implementing support for "dark" / "night" / "high contrast" colour themes, but that is where reflowable / flexible formats are more suitable as they do not get in the way of achieving higher accessibility / usability (notably, EPUB and HTML without any "fixed" styling).

Over the years, this topic has been much discussed over at PDF.js (the library used under the hood by Thorium to render PDF documents):

https://github.com/mozilla/pdf.js

https://mozilla.github.io/pdf.js/web/viewer.html

I believe PDF.js supports Windows "high contrast mode", but I have never tried it myself (I work primarily on Mac OS computers)

Imagine trying to consistently override the styles of such an EPUB (warning, 5MB download):

https://github.com/mozilla/pdf.js/files/1522715/wuppertal_2012.pdf

One common approach is to apply a CSS filter that "inverts" colours (nowadays modern CSS engines also support contrast directives), but there are significant caveats such as treating embedded images appropriately.

Technically it would be near impossible to consistently apply fine-grained CSS "colour" overrides that would result in the expected outcome (e.g. "background" vs. "foreground" colour with adequate contrast) because of overlapping layout boxes, poor semantic structure, etc. So the naive / brute-force CSS "filter" approach makes sense.

I am closing this issue as I believe this is an intractable problem, and I think slightly outside the scope of Thorium given our current development resources (we focus more on EPUB and audiobooks, PDF is a "bonus" feature in my opinion ;)

But please feel free to continue the discussion here, and if there is further interest we can migrate this issue to a proper GitHub "discussion".

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/thorium-reader/issues/577
