### ISSUE TITLE
Localization of TTS for local change of language

### ISSUE THREAD

**Issue by LaZay** [edrlab/thorium-reader#1921]
When foreign words or phrases occur in a born accessible EPUBs, their language must be  specified via a @lang attribute.

Please dynamically change the TTS language to force the foreign language prononciation locally. Take into account the @lang attribute value set on HTML inline `<span>` tag, or ANY block tag (`<p>, <div>, <article>, <table>,` etc.) .

Of course, the flollowing HTML tags without any @lang attributes inherit the value of the @lang attribute value set on their first parent-ancestor that carries a @lang attribute.

Example:
```
<html xmlns:epub="http://www.idpf.org/2007/ops" xmlns="http://www.w3.org/1999/xhtml" xmlns:schema="http://schema.org/" xmlns:php="http://php.net/xsl" lang="fr-FR" xml:lang="fr-FR">
...
<p class="txt_courant_ssalinea">Source : <span lang="en-EN"><cite>The Farming Systems Trial : Celebrating 30 Years</cite>, Rodale Institute</span>, 2011, p. 9-10.</p>
```

**Comment by danielweck** [comment]
Support for multilingual HTML document fragments is already implemented in Thorium.
Could you please share an EPUB with me (privately if needed) so I  can reproduce the bug at my end?
Thank you! ( daniel.weck@gmail.com )

**Comment by LaZay** [comment]
Sure!
Nota: the bug occurs with Thorium Application version 2.2.0.
```
<p class="txt_courant_ssalinea" lang="fr-FR">Source : 
<span lang="fr-FR">En français : <i>The Farming Systems Trial : Celebrating 30 Years</i>, Rodale Institute,</span><br/>
<span lang="en-GB">En anglais : <i>The Farming Systems Trial : Celebrating 30 Years</i>, Rodale Institute,</span> 2011, p. 9-10.</p>
```
Go down here into the TOC:
_1. - À quand un gouvernement écologique mondial ?
De la crise de Cuba au « téléphone rouge » : le dilemme du prisonnier_

Then go to the 1rst table p. 12. The 2nd English source in is vocalized in French.

**Comment by LaZay** [comment]
[9782259313926_modifié_FRetEN.zip](https://github.com/edrlab/thorium-reader/files/10944560/9782259313926_modifie_FRetEN.zip)

**Comment by danielweck** [comment]
Thank you very much for sharing the EPUB. I tested it successfully on Mac OS with Thorium 2.2 as well as the latest automated build from the GitHub "releases" page. The language is correctly switched.

<img width="1552" alt="Screenshot 2023-03-10 at 17 58 48" src="https://user-images.githubusercontent.com/625201/224390389-9b04769c-68f9-450a-a20b-4e587b8c7ded.png">


However, I note that if I force a specific voice by selecting it from the drop-down menu at the top, then that voice is always used regardless of the actual language attribute specified in the HTML markup. This is a known limitation with Thorium's current multilingual support: ideally the user would be able to choose a preferred voice per language, but the UX would be quite confusing. I will see if I can modify the algorithm so that the user-selected voice is only used if the language matches, otherwise reverting back to the "system default" choice.

**Comment by LaZay** [comment]
Sorry I forgot to mention that the bug occurred on Windows. Hummm... 
Could it be related to the TTS available on this OS? Thorium does not embed any TTS in fact, does it?

**Comment by danielweck** [comment]
I "fixed" the bug, or to be precise I modified the TTS voice selection heuristics: now, the user-chosen voice (from the pull-down list at the top) takes precedence over the authored language *only* if there is at least a partial BCP47 locale match. For example, if authored markup is `fr-FR` (i.e. a specific French locale / dialect) but user prefers to listen with a `fr-CA` TTS voice, then the resulting voice selected by Thorium is the user-chosen one (same logic with `en-US` vs. `en-UK`, etc.). If the authored language is `fr` (i.e. no specific locale / dialect), then of course by definition the user can pick any of the available system voices with `fr-*` language. If there isn't at least a partial language match (for example, authored is `fr` but user selected `en-US`), the user-chosen voice is *not* applied, instead Thorium reverts to "system default" (which triggers the operating system to automatically select a matching voice for the utterance language). 

This was tested on Mac OS with your EPUB (thank you again) and with my personal favourite multilingual test publication: Wasteland (French, English, German, Italian, Greek, Latin ...). I am fairly certain that Windows SAPI5 voices work in the exact same way, assuming matching languages are installed in the operating system (Mac OS comes with many language packs by default). Could you please check in a few minutes when Thorium's automated build is ready? Thank you :)

**Comment by danielweck** [comment]
... when this build job is finished:
https://github.com/edrlab/thorium-reader/actions/runs/4387724166/jobs/7683357885

... you will find the updated Thorium installer(s) here:
https://github.com/edrlab/thorium-reader/releases

Thank you for testing. If your test still fails on your computer, then yes it is likely because matching TTS voice languages are missing (you can install them from your Windows 10/11 operating system settings).

**Comment by LaZay** [comment]
Thanks a lot for your reactivity!
I made the right hypothesis then. Yes! :-)
I will test this on Monday now... and will let you know.

**Comment by gautierchomel** [comment]
> Could it be related to the TTS available on this OS? Thorium does not embed any TTS in fact, does it?

Yes, this is documented in [Thorium online documentation FAQ](https://thorium.edrlab.org/docs/400_ressources/430_faq/).
