### ISSUE TITLE
Allow Thorio to use SAPI voices

### ISSUE THREAD

**Issue by errotech** [edrlab/thorium-reader#1934]
I would like to use SAPI voices instead of Onecore voices for the readout function, because I want to use the readout function with a voice I have installed. In general, the selection is better than the Onecore voices

**Comment by danielweck** [comment]
Hello, the synthetic speech voices displayed in Thorium's user interface are provided by the underlying system. To be precise, the full list of available TTS voices is exposed by the Chromium web browser engine (same as Google Chrome, Microsoft Edge, etc.). In Windows, I understand from past user feedback that some SAPI5 / OneCore voices are not exposed due to licensing restrictions which are outside of Thorium's control. I believe that there are registry tricks which may help work around such limitations, but this would have to be the responsibility of end-users, sadly.

**Comment by danielweck** [comment]
Thorium does support SAPI5 TTS voices, however some synthetic speech voices are "hidden" until they are unlocked using Microsoft Windows registry hacks. There are online tutorials / tips that explain how to do this.
Thorium simply relies on the Chromium web browser engine (more specifically, the Javascript Web Speech API) to implement its TTS "readealoud" feature. In other words, if the TTS voices are not exposed in Chromium, then Thorium cannot discover them. By the way, Chromium is also used by Google Chrome and Microsoft Edge (among other examples), but it is not uncommon to see some TTS voices appear in some browsers but not in others. This is the unfortunate state of the art at this point in time.
The most active current discussion on this topic is:
https://github.com/edrlab/thorium-reader/discussions/2095
