### ISSUE TITLE
Equations are not automatically read by screenreader and activating it is difficult

### ISSUE THREAD

**Issue by abhishekbaghel05** [edrlab/thorium-reader#1946]
The equations are rendered nicely when Mathjax is checked in the display settings. But they are not read by screen reader. It says "Math interaction not supported". Then the user needs to right click the equation and activate accessibility option every time. 

Another problem associated with it is when we right click the equation and try select an option using the mouse, the content page automatically scrolls up and down, which make is difficult to select and activate. The automatic scroll should only work if the content is being read by activating inbuilt text to speech.  
 
It will be great if Mathjax accessibility is activated by default in Thorium reader.   

<img width="592" alt="proof" src="https://user-images.githubusercontent.com/23119912/237028701-124a133b-6767-43c6-bc5a-c054ec7cd86d.png">

**Comment by gautierchomel** [comment]
MathML is now shipped with Chromium, the underlying Thorium display engine, next releases of Thorium should not need MathJax anymore. 

Some elements for your consideration:
* Thorium detects if a screen reader is active at startup, make sure it is the case. Starting Screen Reader after Thorium will cause it not being recognized. This is documented in the [Reading with a screen reader section of the Thorium online documentation](https://thorium.edrlab.org/docs/300_accessibility/310_screenreaders/). 
* MathJax accessibility menu is designed for non screen reader users. For NVDA it is recommended to use [MathCAT addon](https://addons.nvda-project.org/addons/MathCAT.en.html). 
* MathJax is not activated by default because of memory consumption.

I also experience the frustrating automatic scrolling with MathJax menu.

**Comment by danielweck** [comment]
Please try with the latest version of Thorium from the test builds available at https://github.com/edrlab/thorium-reader/releases
Thorium version 2.2 only supports MathML via MathJax, and the screen reader compatibility has since improved (also note that the Chromium web browser engine used by Thorium now supports MathML natively so MathJax has become optional)
