### ISSUE TITLE
Thorium not displaying MathML (or fallback images) for EPUB from Pipeline 2

### ISSUE THREAD

**Issue by nicolegaines** [edrlab/thorium-reader#1957]
DAISY recently released a new version of Pipeline 2:
App version: 1.1.0
Engine version: 1.14.14
Engine is running on 127.0.0.1:49152/ws

In using this app to generate EPUB, we found that the tool successfully converted five NIMAS files with MathML into EPUB. However, the MathML content is missing when these files are opened in Thorium v.2.2.0.

We testing two files with MathML 2 and three files with MathML 3. 
We also converted these same NIMAS files into HTML using the same version of the Pipeline. The MathML did successfully display in  Chrome: Version 114.0.5735.199 (Official Build) (64-bit).

So it seems like the MathML itself is okay? Please let me know how we can help with further testing. Thank you!

Nicole Gaines
ngaines@aph.org

**Comment by danielweck** [comment]
Hello, Thorium v2.2.0 doesn't include the recent Chromium web browser engine which provides native support for MathML, you must instead activate the MathJax renderer via the display settings in the reader window. See documentation:

https://thorium.edrlab.org/docs/210_reading/221_maths/

Thorium v2.3.0 will be released soon with native support for MathML rendering, alongside the alternative MathJax implementation. This feature is already available in the automated builds / pre-releases:
https://github.com/edrlab/thorium-reader/releases
(currently building ... should take no more than 15 minutes  :)

**Comment by nicolegaines** [comment]
Thanks, Daniel. This is great news!

Nicole
________________________________

**Comment by danielweck** [comment]
I am closing this issue now, but please do not hesitate to re-open or simply post more feedback and we will reactivate the discussion. I am really interested to hear your comments about the MathJax renderer (which Thorium has been shipping for a long time) and the new native Chromium native MathML renderer.
We know from testing experience that various screen readers + "math plugins" configurations expose the authored MathML and "alt" content differently. Will you be checking as a sighted user or with assistive technology?

**Comment by nicolegaines** [comment]
Thanks, Daniel! At this point we're just checking the visual display of the Math in the EPUB, but we could definitely consider testing with NVDA at a future point. I will say that it's very rare for NIMAS files to include alt text for the math, so it would be a matter of seeing what the ability of the screen reader was to voice the MathML itself. I'm not really sure where the different screen readers are on that support but it would be really great if this was an option. We will keep on the lookout for the new version of Thorium and look forward to checking it out. Thanks again!

Nicole
________________________________

**Comment by danielweck** [comment]
> I will say that it's very rare for NIMAS files to include alt text for the math, so it would be a matter of seeing what the ability of the screen reader was to voice the MathML itself.

Scroll to the bottom of this documentation page:
https://thorium.edrlab.org/docs/210_reading/221_maths/
...and expand the "Read mathematics with NVDA" section. Screen readers usually have "addons" or "plugins" to improve the Math experience.

That being said, MathJax (which ships with Thorium but needs to be explicitly activated by users via the reader settings) generates its own alt text when none is authored at source in the MathML markup. There are different schools of thought about this though, because a Math-aware plugin is capable of navigating down into the actual structure of the Math content island (offering affordances to navigate the equation or at least to extract a meaningful spoken description). So in some cases a top-level alt text may well "dumb down" the narration of the mathematical equation if the TTS experience is limited by the availability of the top-level accessible description. Our internal testing in Thorium indicates that screen readers are capable of not only reading the top-level description but also optionally dig down into the Math markup, thanks to how we structure the XML elements and attributes (MathJax was eagerly placing ARIA hidden instructions into the markup but we now adapt this process to allow access deeper into the Math structure). I hope this makes sense :)

**Comment by nicolegaines** [comment]
Thanks, Daniel. That is really great to know. We probably won't get to it for a few weeks, but we will put it on our radar to check out how the files working with NVDA.

________________________________
