### ISSUE TITLE
DiscardVirtualMemory not available in Windows 7 SP1.

### ISSUE THREAD

**Issue by eric-muller** [edrlab/thorium-reader#1988]
WIndows 7 enterprise, service pack 1.

After installing Thorium 2.3.0, I get this dialog when starting it: 

The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll

**Comment by panaC** [comment]
We are not officially supporting Win7. 

Have you looking for this issue https://github.com/desktop/desktop/issues/17209 from Electron GitHub desktop application.

https://github.com/desktop/desktop/issues/17209#issuecomment-1676340653
It's seems the same issue.

We use electron25 for the 2.3 and since electron23 win7Pro is not supported 
Cf: https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

**Comment by panaC** [comment]
I'm closing the issue, feel free to reopen it

**Comment by eric-muller** [comment]
Ok. You may want to fix <https://www.edrlab.org/software/thorium-reader/>, under "Download Thorium Reader", "Here are links to:",  "The Windows (7, 10, 11) version on the Github platform".

**Comment by danielweck** [comment]
Thank you @eric-muller for noticing the website error, this will be fixed.
