### ISSUE TITLE
[visual bug] certain sections in EPUB documents are misplaced

### ISSUE THREAD

**Issue by verrchu** [edrlab/thorium-reader#2048]
the screenshot is captured on version 2.3.0 on mac

please let me know which other details I can provide
<img width="1792" alt="Screenshot 2023-12-19 at 22 44 34" src="https://github.com/edrlab/thorium-reader/assets/24650632/372417f0-50c1-4145-b16b-b59cdb6fcd48">

**Comment by danielweck** [comment]
This is a Chromium rendering bug that Thorium cannot fix directly. The good news is that Thorium adopts the latest Electron revision available at the time of release so this is likely fixed in v2.4 or in the develop branch. Feel free to reopen this issue if you manage to consistently reproduce the bug. Thank you!
