### ISSUE TITLE
 [New GUI] Comparison Figma Designs/Alpha – Reading screen – Light mode

### ISSUE THREAD

**Issue by Hoppipollala** [edrlab/thorium-reader#2189]
### TTS options – Light mode displays dark mode
<img width="709" alt="Capture d’écran 2024-05-14 à 18 46 39" src="https://github.com/edrlab/thorium-reader/assets/22544556/b6dd8054-5e40-44a6-a0de-975110d08a11">

### TTS buttons
There is no margin between the buttons.
<img width="296" alt="Capture d’écran 2024-05-14 à 18 46 55" src="https://github.com/edrlab/thorium-reader/assets/22544556/cfef3bf9-0eee-4ecf-af7e-9230dbf90fff">

## Reading theme : Night – Text selection
Is there a way to customize the text selection colour, depending on the reading theme selected? The selection colour is not contrasted enough with the text, when using the Night reading theme.
<img width="717" alt="Capture d’écran 2024-05-14 à 18 50 56" src="https://github.com/edrlab/thorium-reader/assets/22544556/cfd9d01a-c2c9-4409-a8b9-1db68058f8c8">

**Comment by danielweck** [comment]
yes, text selection as well as annotation background colours need to be tweaked for contrast ratio in both light and dark modes ... and with other colour themes too!
For the annotations it is more tricky because of the CSS mix blend mode, we might need to allow more configuration then just the RGB triplet.
