### ISSUE TITLE
annotation margin state diverge between webview and readerWin across ressources

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2205]
![image](https://github.com/edrlab/thorium-reader/assets/3198865/57c9ab42-02ed-49f2-b204-d44376d785c8)

change the ressource and come back to it : 

![image](https://github.com/edrlab/thorium-reader/assets/3198865/4c9aabd5-cfc7-44ce-9ca2-a7d14fce4678)

![image](https://github.com/edrlab/thorium-reader/assets/3198865/82e36cfd-1673-4196-b4fe-958692baebf0)

state diverge between the webview and annotation margin checkbox

**Comment by danielweck** [comment]
maybe a good opportunity when fixing this to also implement the 3 options (instead of toggle 2-state on/off margins):

- normal/inline highlights 
- margin indicators (and hover highlights)
- completely hide / do not display highlights at all (zen mode, distraction-free reading, no interference with TTS, Media Overlays, image zoom, and generally-speaking any other text/document interactions)
