### ISSUE TITLE
GUI: how to choose page on keyboard ? 

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2210]
![image](https://github.com/edrlab/thorium-reader/assets/3198865/e32332e6-a7fc-464c-aed7-674f31b3c4e5)

**Comment by danielweck** [comment]
that's a l10n erro I think .. "number on number" isn't correct language.

**Comment by danielweck** [comment]
I am fixing the localization issue, but keyboard navigation / option selection is very strange:
ARROW_DOWN to open the popout list, then ARROW_LEFT (OR RIGHT) to select an option...but this also causes focus steal (modal perimeter becomes outlined) maybe because of React components full refresh? Normally the keyboard focus stays on the selector component.
Other method: instead of ARROW_DOWN just directly ARROW_LEFT (OR RIGHT) on the selector control (without its popout list). Still, same focus steal problem.

**Comment by panaC** [comment]
fixed with https://github.com/edrlab/thorium-reader/commit/2e03ea32000cd147ca0708e33777a97e1ce934f5
SelectBox change to Combobox
