### ISSUE TITLE
Localisation update, translations for Thorium 3.0

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#2219]
Dear contributors, Thorium 3.0 will be released around May 20. The new version proposes a major update of the User Interface; several existing labels have been shortened and new features (mainly annotations) require new labels.

Localization is now eased by the use of GitLocalized, a simple translation tool. As usual, the English locale is the reference. 

Please go to https://gitlocalize.com/repo/9626 and Sign in with Github. Send us you Github ID so that we can add you as "translator". 

Choose your preferred language and open the json file in the interface. On the left side you'll see the English labels, on the right translated labels. Please check the existing translations. News labels will be blank in right cells, please fill them. There is a "comments" feature if a discussion is required on certain terms.  

When it is done, please Create a Review Request (top yellow button).   

# Thorium Localization (l10n) language translations

Information and discussions about localization and language translation process can be found in the [Thorium wiki l10n dedicated page](https://github.com/edrlab/thorium-reader/wiki/Localization-(l10n)-language-translations)

Actual known contributors are :

@horus68
@milliet
@martinpub
@Modeo147
@naglis
@jacoporinaldi
@peaceroad
@panaC
@nvdaes
@HadrienGardeur
@tofi86
@terhol-celia
@maitreya2019
@cary-rowen
@ThanatosDi
@georgegach
@sukiletxe

**Comment by ThanatosDi** [comment]
I already Sign in with Github
https://gitlocalize.com/users/ThanatosDi

**Comment by naglis** [comment]
https://gitlocalize.com/users/naglis

**Comment by danielweck** [comment]
@naglis @ThanatosDi you are now team "translators" :)
Welcome and thank you

**Comment by martinpub** [comment]
Thanks for the localisation call! For this round, @jonaslil will update the Swedish locale.

**Comment by milliet** [comment]
@milliet

I'll make it ASAP,

Cheers
Pedro

Em sex., 17 de mai. de 2024, 04:28, L. Le Meur ***@***.***>
escreveu:

**Comment by izorba** [comment]
https://gr.linkedin.com/in/zorbaioanna
Hi! I have start working, but I am not in the translators list
Can you help me?
Thanks!

**Comment by nvdaes** [comment]
Hello: You can add me for Spanish.
My GitHub ID is: 15809252

**Comment by danielweck** [comment]
@nvdaes @izorba @jonaslil you are now team "translators" :)
Welcome and thank you


@milliet first you need to log into GitLocalize :)

**Comment by horus68** [comment]
@danielweck Can you please update the wiki page https://github.com/edrlab/thorium-reader/wiki/Localization-(l10n)-language-translations to include the link to the Gitlocalize repo https://gitlocalize.com/repo/9626 ?

**Comment by jonaslil** [comment]
Thanks @danielweck, working on it.

By when should the translation be submitted to be included in version 3.0?

**Comment by nvdaes** [comment]
@danielweck , I've finished the spanish translation, though in the GitLocalize webpage appears 78%. Perhaps some words are equal.
Annotations is an amazing feature. Thanks for your had and nice work.

**Comment by horus68** [comment]
Something broken... all translations updates gone. I had 100% done, same as Slovenian... now it went down again to 46%
My already submitted translation also was deleted! (error 500 when accessing it on Gitlocalize) :(

Maybe the language files were updated on the GITHUB project directly from your local computer?
I believe that only the master english language files should be updated, the translations should be updated form the GITLOCALIZE project using their own PR creator

**Comment by danielweck** [comment]
interesting ... there are new commits in the develop branch, and GitLocalize synchronizes its state with GitHub so maybe that's the cause of the refresh. I'll see if anything was lost, give me a minute...

**Comment by milliet** [comment]
The same with the Brazilian Portuguese. I've completed 100%. Now it shows
34%.

I don't look at it now but I'll see when I get home.



Em sex., 17 de mai. de 2024, 17:06, Daniel Weck ***@***.***>
escreveu:

**Comment by danielweck** [comment]
To those of you who submitted your translation as "Review Request", I am horrified and mortified to discover that your work seems to have vanished from GitLocalize!! I am posting on their issue tracker right now, trying to figure out if this is an exceptional bug, or a "normal" part of the workflow which means that whenever changes are pushed to the develop branch (even if only a minor update of the JSON locales) we must approve ALL the Review Requests before pushing our code, otherwise GitLocalize nukes existing pending work ... I know this sounds stupid, given that the system is supposed to handle conflict and help users / translators identify diverged strings and  merge resolutions.
I will post screenshots below to show you what I see in GitLocalize, as an admin...

**Comment by danielweck** [comment]
> Even with frequent updates to your project, GitLocalize keeps localization stress-free.

https://docs.gitlocalize.com/about.html

**Comment by danielweck** [comment]
@nvdaes your Spanish data was still in GitLocalize as a pending / open Review Request, so I quickly created a Pull Request here in GitHub https://github.com/edrlab/thorium-reader/pull/2231

**Comment by milliet** [comment]
Hi Daniel,

It happens!

Just tell me when it is safe to make it again.

See you soon!

Pedro

Em sex., 17 de mai. de 2024, 18:03, Daniel Weck ***@***.***>
escreveu:

**Comment by danielweck** [comment]
@nvdaes your Spanish translation is indeed at 78%, in fact I see empty strings in the GitLocalize user interface. I hope this is not too hard with your screen reader: https://gitlocalize.com/repo/9626/es/src/resources/locales/en.json

**Comment by danielweck** [comment]
So, I went back to all the notification emails I received from GitLocalize (because their website admin panel doesn't show this) and I found the following:

* @ThanatosDi I am afraid your `zh-tw` data is lost (error 500 when I click on the Review Request menu) https://gitlocalize.com/repo/9626/zh-TW/review/71403
* @horus68 same with `pt-pt` https://gitlocalize.com/repo/9626/pt-PT/review/71404
* @naglis same with `lt` https://gitlocalize.com/repo/9626/lt/review/71410
* @milliet same story with `pt-br` https://gitlocalize.com/repo/9626/pt-br/review/71411
* @nvdaes your `es` data survived, I suspect because you translated after we pushed changes to develop (not sure though) https://gitlocalize.com/repo/9626/es/review/71417

**Comment by danielweck** [comment]
I posted my feedback in the GitLocalize GitHub issue tracker: https://github.com/gitlocalize/feedback/issues/138

**Comment by danielweck** [comment]
Looking at Thorium's JSON locales changelog timeline (timestamps), I am now fairly certain that the reason why @nvdaes Spanish data survived is because she posted her work after we pushed changes, all other translators posted their Review Request before:
https://github.com/edrlab/thorium-reader/commit/b3e2d8c444ac6d20ff615e133f16abde84c551e5#diff-da7119d1c8c008d685d71dd864febae06da76c518a53683034f8ec52fcece6d8

**Comment by danielweck** [comment]
@llemeurfr @panaC if indeed the issue here is that modifying any JSON locale other than the reference `en.json` causes data loss on GitLocalize servers (for pending Review Requests that are not yet converted to GitHub Pull Requests, at least from what I can deduct)...then we have a big problem because as previously discussed, the JSON generated by GitLocalize is not formatted as per our existing conventions (not just indentation, but also empty strings that disappear totally ... maybe even lack of alphanumerical recursive key sorting), which breaks our own code diff tracking process. Our expected workflow was to continue as before: "fork" the translator's PR to normalise the contributed JSON and merge into the develop branch once fully verified. Same with new locales, except extra work / plumbing in the codebase.
One solution is of course for us to modify our existing conventions in order to align with GitLocalize expectations: never modify JSON locales other than `en.json`, match JSON indentation by tweaking our script / tools, also handle missing keys as empty strings (I suspect alphanumerical key sorting will not be enforced by GitLocalize either, so that's that).
My gut instinct is that competitor tools will pose similar problems, or at least impose similar constraints. We decided to go with GitLocalize for its ease-of-use and minimalist feature set, I remain confident that this is a good choice in that respect. I am now waiting for their response, just to make sure my assumptions are correct.

**Comment by nvdaes** [comment]
@danielweck , I tried to translate all the strings, but for any reason, perhaps because I hadn't never used this platform (Gitlocalize), I see that some of them are not preserved. But when a PR is in review translators cannot edit it.
Can you please change the state of the PR to finish the spanish translation?
Also, if you can tell me if there is some visual or alignment difference to navigate directly to strings which need to be translated, I'd try to use my screen reader to do it, since now it has the ability to navigate to same or different style text. I don't know if this will work in this table.
Another alternative is if Poedit can be used, since untranslated strings meaybe grouped at the start of the file.
Thanks.

**Comment by cary-rowen** [comment]
Hi @danielweck 

https://gitlocalize.com/users/cary-rowen

Please help me register as a Simplified Chinese translator.

Thanks

**Comment by ThanatosDi** [comment]
@danielweck So, we need to re translation or waiting GitLocalize answer feedback?

**Comment by danielweck** [comment]
@cary-rowen I added you to the team as a "translator". Welcome and thank you for your past and future contributions!

**Comment by danielweck** [comment]
@ThanatosDi there is a "download" button in GitLocalize user interface, so a manual backup is possible. Now that we know about the GitLocalize data loss bug, we are going to be careful merging JSON locale files into the `develop` branch!

<img width="753" alt="Screenshot 2024-05-18 at 19 13 50" src="https://github.com/edrlab/thorium-reader/assets/625201/af85c485-7d73-4ef6-adb0-356e7fc17a07">

**Comment by milliet** [comment]
Hi Daniel,

Should I redo the translation now?
If possible I'll do it later today.

Best

Pedro

Em sáb., 18 de mai. de 2024, 15:16, Daniel Weck ***@***.***>
escreveu:

**Comment by danielweck** [comment]
yes please, redo if you have time. I am not hopeful that GitLocalize will be able to recover your data from their systems (yet, I assume they host a Git copy of the submitted translator work, who knows...).

**Comment by ThanatosDi** [comment]
> @ThanatosDi there is a "download" button in GitLocalize user interface, so a manual backup is possible. Now that we know about the GitLocalize data loss bug, we are going to be careful merging JSON locale files into the `develop` branch!
> 
> <img alt="Screenshot 2024-05-18 at 19 13 50" width="753" src="https://private-user-images.githubusercontent.com/625201/331824222-af85c485-7d73-4ef6-adb0-356e7fc17a07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjg3MDQsIm5iZiI6MTcxNjEyODQwNCwicGF0aCI6Ii82MjUyMDEvMzMxODI0MjIyLWFmODVjNDg1LTdkNzMtNGVmNi1hZGIwLTM1NmU3ZmMxN2EwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQxNDIwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Yzg0YjI5NDY5YWJmNWZiNGE5ZjFjNDQ3NjhjNjFjNzE3YTEzMjA3ZWYzNWE3OWJkMzAzMGM5MTQ5ODNiNDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WeB_QDgZUAaTpMPuc03bQZDKMKE2MikuOfjh6QdJqA8">

After I finished translation and create a new PR, I can't download. GitLocalize return 500 ERROR

![image](https://github.com/edrlab/thorium-reader/assets/12424898/88173937-52e3-476c-aff6-d38635c9da99)

**Comment by horus68** [comment]
To make things more efficient the project needs to assign one or more Moderators to each language. This way admins don't need to approve the "Review requests" from all translators. Moderators can approve and submit PR to the GITHUB repository.

Users with the "**Moderators**" role (selected by language) can **translate** and **approve** translations done by users with the "**Translator**" role.
Moderators can also (this is relevant) create a PR to GITHUB repo, so no data will be lost!
Translators can only translate (in any language) and place "Review requests" for their translations. The review requests need to be approved by an admin or a moderator. Only then a PR can be created (by the admin or the language moderator). The PR its very simple to be created, no technical knowledge on the way a repository works!

How to create managers? After selecting the user if the role is Moderator a language selector will show!
![2024-05-19 15_43_38-GitLocalize - Continuous Localization for GitHub Projects](https://github.com/edrlab/thorium-reader/assets/3055443/a9b82e6a-8145-4f52-8e08-e8a30603660c)

Note: translator role is generic, not assigned to a specific language. Moderator role is specific for a language (if someone need to be moderator for two languages the project admin needs to add the user twice in the Manage page, once for each role/language.

From the FAQ
> Translators can only add or update translations and create review requests (send translations to Language Moderators for review). They will not be able to send pull requests to GitHub.
> Language Moderators review translations submitted by translators, can edit translations that are awaiting review and send translations to GitHub (create pull requests) - but only for the language they are moderating.

The PR screens:
![2024-05-17 20_26_21-GitLocalize - Continuous Localization for GitHub Projects](https://github.com/edrlab/thorium-reader/assets/3055443/46015ce2-45ff-4ac5-8b3b-2d812f602006)

![2024-05-17 20_27_11-GitLocalize - Continuous Localization for GitHub Projects](https://github.com/edrlab/thorium-reader/assets/3055443/c2fb2e88-5ddc-43db-ac86-d106ea5a2a88)

**Comment by jonaslil** [comment]
The Swedish translation is complete but I haven't submitted it for review yet. I can't see any download button in the interface, does it appear after the review request?

Any info on the schedule would be welcome. My colleagues will handle the Finnish locale, there is a draft but nothing is entered on GitLocalize yet.

**Comment by gautierchomel** [comment]
We have a wonderful localization team! Thanks each of you for your involvement. I agree with @horus68 that we need to add moderators per language and because this "Review request" step is about language, not technique, it makes sense to have each of you moderator for the language you translate. 
To avoid data loss, you should push a Pull Request thru Gitlocalize interface as soon as you are done. Any correction can always be done later by restarting the process (translate, review request, pull request). 
I was able to add the moderator role for 
@horus68
@milliet 
@naglis
@peaceroad
@cary-rowen
@ThanatosDi
@jonaslil 
@izorba 
@nvdaes

**Comment by MiiaKirsi** [comment]
Hello! As @jonaslil mentioned earlier, Finnish version will be taken care of by me and my colleague Kirsi. Will be starting to enter the translations to GitLocalize today. If it's not too much of a hassle, I guess I would be the one to add as a moderator for Finnish.

**Comment by gautierchomel** [comment]
> [...] I would be the one to add as a moderator for Finnish.
Done.

**Comment by Modeo147** [comment]
Hello. You can add me for Russian translator.

**Comment by KirsiYl** [comment]
Could you kindly add me as a translator (for Finnish)?

**Comment by cary-rowen** [comment]
Hi @gautierchomel 
I would like to be the moderator of Simplified Chinese Translation

**Comment by gautierchomel** [comment]
> Hi @gautierchomel I would like to be the moderator of Simplified Chinese Translation

You are: https://gitlocalize.com/repo/9626/zh-CN/src/resources/locales/en.json

**Comment by gautierchomel** [comment]
> Can you please update the wiki page https://github.com/edrlab/thorium-reader/wiki/Localization-(l10n)-language-translations to include the link to the Gitlocalize repo https://gitlocalize.com/repo/9626 ?

Done.

**Comment by milliet** [comment]
Hi!

Brazilian Portuguese translation done. Pull request sent.

Best

Pedro

Pedro Milliet - fenixeditorial.com.br - +55 11 980899000

Em seg., 20 de mai. de 2024, 10:00, Gautier Chomel ***@***.***>
escreveu:

**Comment by tofi86** [comment]
@danielweck you can add me to the translators team for german.

**Comment by gautierchomel** [comment]
@tofi86 done: https://gitlocalize.com/repo/9626/de

**Comment by danielweck** [comment]
Interesting follow-up at the GitLocalize feedback tracker:
https://github.com/gitlocalize/feedback/issues/138#issuecomment-2120815428

**Comment by danielweck** [comment]
To all active translators, I did an interesting test: I made a minor improvement to the English label "Don't show anymore" which is now "Don't show again". The GitLocalize internal state was then automatically synchronized with the upstream Thorium `develop` branch, and the translations that were at 100% became 99% (Greek, French, Japanese, Portuguese Brazil and Portugal, Swedish and Chinese Taiwan / Traditional). So I explored the GitLocalize user interface and I clicked the "filter" icon and I selected the "untranslated segments" option. This immediately showed my new English tweaked phrase but the other locale string was empty. So I clicked inside the edit box and the "translation memory" choice appeared at the bottom, giving me access to the exact already-translated label that we merged via Pull Request. So I selected it because the semantic nuance in English is very minor (just slightly better style and shorter string). French was an exception as there was no "translation memory" (not sure why). The Chinese language had two choices in "translation memory" so I made sure to select the most current one that matched the develop branch. I clicked on "submit" and after making sure to "sync" the repository from the GitLocalize interface, all these languages went back to 100%. Good to see that the minor English change didn't majorly interfere with existing translations, we just have to remember to click on the empty text editor and manually reselect text from "translation memory" to avoid typing everything in again. @nvdaes as you are a screen reader user I am not sure if you can access the proposed choices by GitLocalize. Thank you all!

**Comment by naglis** [comment]
Thank you for this idea @danielweck. I don't see the "translation memory" option in the translation page for the Lithuanian language, but I am able to find my previously translated strings in the [Search tab](https://gitlocalize.com/repo/9626/search?query=&search_by=translation_memory) by selecting to search in the "Translation Memory". This is useful to restore the long strings.
![Screenshot 2024-05-21 at 07-37-54 GitLocalize - Continuous Localization for GitHub Projects](https://github.com/edrlab/thorium-reader/assets/827324/a2d17349-13c3-454d-a6f1-508e7b7a9771)

**Comment by gautierchomel** [comment]
Hello, we have one week extra to proceed to translations!

We are missing: 

- [Bulgarian](https://gitlocalize.com/repo/9626/bg/src/resources/locales/en.json) @openm1nd maybe?
- [Danish](https://gitlocalize.com/repo/9626/da/src/resources/locales/en.json) @notalib, @ddfreiling, @TimArborealis @MyGulstad maybe?
- [Croatian](https://gitlocalize.com/repo/9626/hr/src/resources/locales/en.json) @Celeruk maybe?
- [Italian](https://gitlocalize.com/repo/9626/it/src/resources/locales/en.json) @jacoporinaldi maybe?
- [Georgian](https://gitlocalize.com/repo/9626/ka/src/resources/locales/en.json) @georgegach maybe?
- [Korean](https://gitlocalize.com/repo/9626/ko/src/resources/locales/en.json)
- [Dutch](https://gitlocalize.com/repo/9626/nl/src/resources/locales/en.json) @bitsgalore maybe?

**Comment by gautierchomel** [comment]
Also, we'll update the wiki page for all translators to highlight your work better. 

To that end we're collecting words in Localization wiki #2369.

Alternatively, you can drop us a message by email.

**Comment by ddfreiling** [comment]
@gautierchomel Thanks for the bat signal, I'd love to complete the Danish translation for Thorium 3!
I have logged into GitLocalize on this GitHub ID.

**Comment by gautierchomel** [comment]
> @gautierchomel Thanks for the bat signal, I'd love to complete the Danish translation for Thorium 3!
> I have logged into GitLocalize on this GitHub ID.

You are now a translator and moderator for Danish.

**Comment by llemeurfr** [comment]
This issue can now be closed. Some languages are not fully translated, but we have to release v3.0. Labels will be completed for v3.1.

**Comment by izorba** [comment]
When it would be published Thorium 3.0?
https://www.edrlab.org/software/thorium-reader/

![image](https://github.com/user-attachments/assets/1a903eea-37d8-4930-9086-b6fdcf095a16)

Thank you!

**Comment by horus68** [comment]
> When it would be published Thorium 3.0? https://www.edrlab.org/software/thorium-reader/
> Thank you!
That page text needs to be updated.
Version 3.0.0 was released on 26 June 2024.

You can use this download page: 
https://thorium.edrlab.org/

Or find latest releases here:
https://github.com/edrlab/thorium-reader/releases/

**Comment by gautierchomel** [comment]
> That page text needs to be updated.

Done. Thx for pointing out.
