### ISSUE TITLE
Backlinks in Footnote Popups

### ISSUE THREAD

**Issue by gregoriopellegrino** [edrlab/thorium-reader#2280]
When footnotes are displayed in a popup window, the current behavior includes showing the backlink to the footnote reference. However, this backlink in popup may cause confusion and lacks functionality within the popup context, as the user experience (UX) of a popup window doesn't support the intended purpose of a backlink.

## Proposed Solution
We propose hiding the backlink elements within the footnote popups by leveraging the semantics of the `epub:type` and `role` attributes. This approach would ensure a cleaner and more user-friendly display of footnote content within the popup window.

**Comment by danielweck** [comment]
Hello, I think you are referring to authored backlinks inside endnotes / footnotes content, which also appear inside the popup modal rendered by Thorium (because we just take the targeted HTML fragment and render it inside a modal portal). What `epub:type` or `role` values are you suggesting we use to selectively hide the backlink? Thorium's implementation of "popup footnotes" is that we try to "make things work" within the content island rendered in isolation inside the pop out modal. This includes images, styles, and links (there is a known issue with TTS readaloud not working as one would expect, but that's a hard problem to solve, and quite separate to this discussion). So there can be any links inside footnotes, we make sure that they work just as if they were rendered inline the original authored document (even though we present the fragment inside a disconnected modal portal).

**Comment by gregoriopellegrino** [comment]
> Hello, I think you are referring to authored backlinks inside endnotes / footnotes content, which also appear inside the popup modal rendered by Thorium (because we just take the targeted HTML fragment and render it inside a modal portal).

Right.

> What `epub:type` or `role` values are you suggesting we use to selectively hide the backlink? Thorium's implementation of "popup footnotes" is that we try to "make things work" within the content island rendered in isolation inside the pop out modal.

`epub:type = "backlink"` and `role = "doc-backlink"`.

**Comment by danielweck** [comment]
great, so discovery heuristics are clear :) 
(no hacks required)

is there a sample EPUB I could use to test the implementation?
