### ISSUE TITLE
In RTL vertical writing mode, the leftmost column of text may be cut off.

### ISSUE THREAD

**Issue by peaceroad** [edrlab/thorium-reader#2353]
In the current environment (3.0-alpha), when displaying an RTL Japanese book in vertical writing, the sentence displayed on the far left may be cut off.
The attached image shows the EPUB sample "Kusamakura".
https://idpf.github.io/epub3-samples/30/samples.html#Kusamakura
You may be aware of this problem, but I'll submit it just in case.

![image](https://github.com/edrlab/thorium-reader/assets/1066782/7781f610-dc9f-408a-9efe-6012baf33096)

**Comment by danielweck** [comment]
Hello, thank you for reporting this. This is not a bug, any other language / script in scroll mode (horizontal or vertical ) would potentially have text sentences partially out of viewport at the beginning or the end of the scroll extent.
I think you are referring / comparing with true paginated mode. There is no paginated mode in Japanese (or any vertical writing mode locale) due to technical limitations / layout issues with CSS columns. What you see here is horizontal scroll.

**Comment by peaceroad** [comment]
I see, I didn't realize that: Vertical display is in scroll mode, so the last text may be cut off if it extends beyond the rendering area.
Thank you for explaining even though you are busy!

**Comment by danielweck** [comment]
you're welcome. we are very happy to receive feedback / suggestions from people who can share knowledge / expertise about their language (or other domains) which the core development might lack :)
