### ISSUE TITLE
Is it possible to lock pagination to the bottom of the OPDS browsing viewport ? 

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2372]
![image](https://github.com/edrlab/thorium-reader/assets/3198865/168cb504-c3c8-4fe2-8daa-fb7cec1a97f6)

**Comment by arthur-lemeur** [comment]
I got a solution but it's not perfect. I can detect if there is scroll in the opds_browserResults div. If there is, the pagination is placed at the end of the content and if there's not it is place at the bottom of the screen (position fixed). But if you're in the view where there are the categories filters if you only got one publication there is still scrolling because of the categories entries so the pagination still is at the end of the only publication (as you can see in the screenshots)..
What do you think ?

![Image](https://github.com/edrlab/thorium-reader/assets/113124595/da257b46-73ee-496c-ab41-07c8720daac4)

![Image](https://github.com/edrlab/thorium-reader/assets/113124595/ccbdd8de-4e6f-4013-a8c2-05d52881e97d)

![Image](https://github.com/edrlab/thorium-reader/assets/113124595/ec22c0b3-0300-404b-aa92-a28c866dd056)
