### ISSUE TITLE
Thorium -2.4.1.dmg can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by TADatTRT** [edrlab/thorium-reader#2425]
i can't get past this message. Thank you for any advice or update! ---tad.
"This software needs to be updated. Contact the developer for more information.

Firefox downloaded this file today at 10:48 AM from thorium.edrlab.org."

**Comment by danielweck** [comment]
hello, could you please try Thorium 2.4.2 ?

**Comment by danielweck** [comment]
Closing due to lack of feedback, but please feel free to add a comment and we will reactivate this discussion :)

**Comment by TADatTRT** [comment]
Lack of feedback? Sorry, I thought I sent a message saying that I downloaded the 2.4.2 installer and got the same message.

Sent from my iPhone

On Jun 12, 2024, at 03:17, Daniel Weck ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Closing due to lack of feedback, but please feel free to add a comment and we will reactivate this discussion :)

**Comment by danielweck** [comment]
what version of MacOS are you using, please?

**Comment by TADatTRT** [comment]
10.14.6; when I tried installing 2.4.2 on this machine and it failed, this morning I tried on my 13.6.1 machine and it worked. Sorry for the bother. Worth writing a caution re minimum kit needed to run Thorium 2.4.2? —-tad.


Sent from my iPhone

On Jun 14, 2024, at 00:33, Daniel Weck ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

what version of MacOS are you using, please?

**Comment by danielweck** [comment]
Thank you for letting us know. Thorium's minimum hardware/software requirements are largely dictated by the Electron application framework, and by Electron Builder which is the component that packages Thorium for Windows/Linux/Mac and orchestrates code-signing and notarizing of the executables/installers where applicable (EDRLab Extended Validation certificates are used for Windows and MacOS so there shouldn't be any warning/error messages). I wouldn't be surprised if old versions of MacOS had become incompatible with Apple's latest (more stringent) security policies. I noticed different behaviours between Intel and Apple Silicon ARM hardware too, with the same Thorium release. Microsoft is deprecating Windows 10 so I expect some backwards compatibility issues in the near future too. As for Linux, there's the issue of incompatible libc versions as well. I am afraid the safe path is to upgrade to recent / supported operating systems (not just for Thorium, to be fair, but also generally-speaking because of security patches etc.).

**Comment by TADatTRT** [comment]
Thanks for this. Security is a reasonable justification for planned obsolescence, but I’m sure it has a silver lining for MS, Apple, and others. But it’s a pain for end-users who aren’t looking for the bells and whistles on offer w/ the latest and greatest. And who don’t feel confident to switch to, say, Linux, if that’s a viable option. Cheers, —-tad.


Sent from my iPhone

On Jun 14, 2024, at 09:43, Daniel Weck ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Thank you for letting us know. Thorium's minimum hardware/software requirements are largely dictated by the Electron application framework, and by Electron Builder which is the component that packages Thorium for Windows/Linux/Mac and orchestrates code-signing and notarizing of the executables/installers where applicable (EDRLab Extended Validation certificates are used for Windows and MacOS so there shouldn't be any warning/error messages). I wouldn't be surprised if old versions of MacOS had become incompatible with Apple's latest (more stringent) security policies. I noticed different behaviours between Intel and Apple Silicon ARM hardware too, with the same Thorium release. Microsoft is deprecating Windows 10 so I expect some backwards compatibility issues in the near future too. As for Linux, there's the issue of incompatible libc versions as well. I am afraid the safe path is to upgrade to recent / supported operating systems (not just for Thorium, to be fair, but also generally-speaking because of security patches etc.).
