### ISSUE TITLE
Microsoft Defender SmartScreen installer protection

### ISSUE THREAD

**Issue by horus68** [edrlab/thorium-reader#2464]
Microsoft Defender SmartScreen protection pops up on Windows 10
Note: my screens are in Portuguese but I transcribed the english words found in similar screens on the web

Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.
![2024-06-24 17_04_09-](https://github.com/edrlab/thorium-reader/assets/3055443/7bd4c9c5-7001-4826-8dac-6c790c721c3a)

Then we need to click the link "More Info" (Mais informações) and then click "Run Anyway" (Executar mesmo assim) 
![2024-06-24 17_04_16-](https://github.com/edrlab/thorium-reader/assets/3055443/a894df99-1b2c-4461-8401-6716c93f6bc1)

Solution? See here:
Your newly created application is safe and signed but SmartScreen servers haven't probably identified it as safe yet.
How do I dispute the detection of my program?
https://learn.microsoft.com/en-us/defender-xdr/submission-guide#how-do-i-dispute-the-detection-of-my-program

System: windows 10
Thorium: latest alpha

**Comment by danielweck** [comment]
Hello, pre-release / alpha builds are automatically created from the develop branch (i.e. latest code) and uploaded to GitHub. These installers are not code-signed with the EDRLab certificate, which is why they are flagged as "unsafe". On Linux there is no requirement of code signing. The Windows installer gives the user a warning message about trust / safety verification (which the user can ignore by choosing "more information" and "run anyway"). On MacOS the technique to bypass the warning on Intel machines is to launch the app twice (on second time, Apple displays an "open" button), and on M1/M2/M3 Apple Silicon computers there is an additional command line step to bypass Apple's aggressive "quarantine" blocker:
`xattr -dr com.apple.quarantine "/Applications/Thorium.app"`
