### ISSUE TITLE
[CSS] input type=text outline

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2578]
![image](https://github.com/user-attachments/assets/9c18f24b-43a0-4cb4-852b-c4e47a79e75a)

see example on getpocket.com 

![image](https://github.com/user-attachments/assets/f08eacba-7b17-418e-9cfd-8dcf3cd6c7ff)

**Comment by danielweck** [comment]
I think that the global focus mixin needs to be removed? (not sure if there are local CSS rules for each component?) The global mixin was inherited from pre-3.0 Thorium when we had a thick blue high-contrast keyboard focus outline everywhere (the 3.0 redesign replaced this with the more pastel theme in order to offer consistent visuals across the GUI). As you know I prefer the old vivid blue outline but I am in a minority ;)

**Comment by panaC** [comment]
For the moment, I just close this issue with the [PR](https://github.com/edrlab/thorium-reader/pull/2576), the Figma design is respected and with the last fixes from Arthur, it is visually better. Let's continue the discussion about this global mixin in a next time with Arthur :)

**Comment by danielweck** [comment]
oh yeah sure, I align with the team consensus, I just wanted to explain the origins of the mixin (which may or may not be needed in the context of the SASS / JSX components refactoring, I just don't know :)
