### ISSUE TITLE
Back to bookshelf button closes the reading window

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#2696]
`reader.navigation.backHomeTitle` "back to bookshelf" button closes the reading window and brings the library window front, resulting in users searching for the reading window. 

The best choice would be to keep the reading window open. Otherwise, the button label should specify the behaviour "back to bookshelf (will close this ebook)".

**Comment by panaC** [comment]
not anymore as far i know, There was decided between us far ago. Is it useful to relaunch the debate now ? :)

**Comment by danielweck** [comment]
If there is one reader window, it gets closed and the library window comes to the foreground.
If there is more than one reader window, the library window comes to the foreground but all other reader windows remain as they are.
IIRC

**Comment by gautierchomel** [comment]
> Is it useful to relaunch the debate now ?

Yes, as users get lost searching for the window. 

At least the button label should indicate what will happen.

**Comment by llemeurfr** [comment]
I disagree with changing the affordance behaviour, which has been there from the start and nobody complained so far.

I agree that the label can be made more explicit. The behaviour of the button is exactly the same as the system-level "close the window" button (it also brings the personal library forward). And the fact that the library is put forward is the ice on the cake; it is good for the user but we don't need to expose it in the label. Therefore we'll simple label the action "close the window". We'll keep the "library" icon because it is nice looking and relevant for the experience (the library come on the front).

**Comment by gautierchomel** [comment]
What about _"Close this reading window (back to bookshelf)"_? So users don't get confused between two buttons with the same name in different places.

**Comment by gautierchomel** [comment]
Preview: 
![image](https://github.com/user-attachments/assets/465ffecd-b508-47c9-af92-c061ea2edb11)

**Comment by gautierchomel** [comment]
> If there is more than one reader window, the library window comes to the foreground but all other reader windows remain as they are.

Tested, with two reading windows opened, the button closes the one from which it was activated (and bookshelf windows come to front).

**Comment by llemeurfr** [comment]
ok ok, I validate "Close this reading window (back to bookshelf)".
