### ISSUE TITLE
Open file from CLI: add options

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#438]
When opening a file from the command line, one can already add a -- silent parameter indicating that the ebook is imported in the library but the browser windows is not opened. 

Currently, if the ebooks already exists in the library, it is duplicated. This is usually not the expected behavior. 

This proposal defines three new parameters: 
-- replace: if the ebook already exists in the library, it is replaced by the new instance. 
-- display:  if the ebook already exists in the library, the new instance is not imported but the existing instance is displayed in a browser window. 
-- duplicate:  the ebook is added into the library even if it is a duplicate; the identifier of the ebook is not tested. 

Note: the notion of identity of an ebook (what makes 2 ebooks "the same") is discussed elsewhere.

**Comment by danielweck** [comment]
ignoring the CLi for a moment: we also need to design a UX for when double-click / open-with on a publication: ask user once (dialog prompt) and remember preference (duplicate, overwrite, open existing) ... I assume after import the book is automatically loaded in a reader view.
Then, back to the CLi: when the --silent flag is activated, the assumption is that this is for automated imports (with a default of either overwrite or duplicate). Without --silent, there are more options in terms of UX ... and because double-click / open-with is implemented with CLi under the hood (except for the MacOS open-file event), then there is some overlap and potentially some UX conflicts.

**Comment by panaC** [comment]
I suppose that isn't a priority @llemeurfr 
may i removing my assignment.

**Comment by llemeurfr** [comment]
ok this feature not a priority, let's move it to the icebox but keep the issue open.

**Comment by danielweck** [comment]
bug triage: meta-issue can be closed, we are resolving bugs in current CLI implementation
