### ISSUE TITLE
LCP / UX: renew or return a loan

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#892]
Only the book info panel opened from the drop-down menu in the Catalog view can be used to extend a loan or make an early return. The same info panel, opened from the Reader view, does not have these actions. 

Technical constraint: Currently we can't update the LCP license when the book is open. 

Solution : review the ergonomics of the app; best solution may be to place the Renew / Return / Delete buttons directly in the drop-down menu.

**Comment by danielweck** [comment]
> best solution may be to place the Renew / Return / Delete buttons directly in the drop-down menu.

I do not think this is a good idea, for the same reason that the "borrow" etc. OPDS links are not presented in the popup menu: whenever the "publication info" modal dialog box appears, there is a circular indeterminate progress indicator due to asynchronous HTTP fetching of additional OPDS publication / metadata. For example, a user logged-in via OAuth has access to additional OPDS-supplied information which is not supplied in the initial feed, such as a usable "borrow" link that replaces the initial "sample" link. This information is obtained via a level of indirection (i.e. HTTP `GET` request) which responds with a more complete OPDS "publication" feed.

A similar pattern occurs with LCP-protected publications: Thorium performs a check for potential LSD updates at key points during the UX "lifecycle" / flow, such as before attempting to open a publication for reading, or before displaying the "publication info" box. This way, we can guarantee that the LCP start/end dates (for example) are up to date, and in case the publication is "blocked" (e.g. revoked license) we can prevent the opening, or simply display relevant messages in the "publication info" box.

More to the point: both the `renew` and `return` links can "disappear" once a LCP license gets updated via LSD, so I think it is a bad idea to display them statically in the popup menu. They can however be reliably displayed in the modal "publication info" box, thanks to the async LSD check performed before displaying the popup dialog.

**Comment by danielweck** [comment]
> Technical constraint: Currently we can't update the LCP license when the book is open.

Correct. Thorium automatically closes opened readers when the publication artefact (i.e. the underlying EPUB file stored in `publications/UUID/book.epub`) is about to be injected with a fresh `META-INF/license.lcpl`.

**Comment by danielweck** [comment]
Closing this one. Over time the UI has evolved and the experience is reasonably good now.
