### ISSUE TITLE
LCP: handle the html renewal mode

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#894]
If the server serves an html page as renew link in the status document, the app fails, displaying: 

<img width="320" alt="Capture d'écran 2019-12-18 14 28 26" src="https://user-images.githubusercontent.com/14943186/71090216-cca4ea80-21a2-11ea-89f3-ac583de852d5.png">

The app should handle this case, display the html page full screen in the app (this is where the loan extension request is processed), propose a close button, return to the initial state (the info panel or the library view depending the chosen UX).

**Comment by danielweck** [comment]
HTML `renew` (i.e. instead of the LSD HTTP `POST` request) is currently handled by opening an external web browser. We simply test for the `text/html` or `application/xml+xhtml` link `type` (which maps to HTTP `content-type` header).
The screenshot above shows HTTP status code `405` ( https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405 ) which suggests that an incorrect `POST` / `GET` / `PUT` request was issued to the LSD server.
@llemeurfr could you please share the publication that exposes such HTML `renew` link? Thank you!

**Comment by danielweck** [comment]
Note to devs (LSD link `type` check):
https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/services/lcp.ts#L323-L325

**Comment by danielweck** [comment]
Laurent, it would be great if the refactored / latest evolution of the LCP server (Go implementation) could include HTML renew links, for testing?

**Comment by llemeurfr** [comment]
The LCP Server can easily be configured so that Status documents contain a specific renew URL. The corresponding config parameter is license_status/renew_page_url. 

I tested the solution with a simple URL. A new tab is open, great.
