### ISSUE TITLE
book info panel: badly displayed japanese characters

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#896]
See this Japanese bloc article: 
https://www.moongift.jp/2019/11/thorium-reader-%e3%82%af%e3%83%ad%e3%82%b9%e3%83%97%e3%83%a9%e3%83%83%e3%83%88%e3%83%95%e3%82%a9%e3%83%bc%e3%83%a0%e3%81%a7%e5%8b%95%e4%bd%9c%e3%81%99%e3%82%8b%e9%9b%bb%e5%ad%90%e6%9b%b8%e7%b1%8d/

**Comment by danielweck** [comment]
![open-source-thorium reader-1 0fc49fac360f05f61d0e9145b0f75118](https://user-images.githubusercontent.com/625201/71160127-e72ca180-223e-11ea-876c-97ef6d6b569d.png)

**Comment by danielweck** [comment]
No problems with this IDPF sample EPUB, so I suspect their XML UTF8 encoding in `package.opf` is incorrect:

http://idpf.github.io/epub3-samples/30/samples.html#jlreq
=>
https://github.com/IDPF/epub3-samples/releases/download/20170606/jlreq-in-japanese.epub

https://github.com/IDPF/epub3-samples/blob/master/30/jlreq-in-japanese/OEBPS/jlreq_ja.opf
=>
```
<dc:description>この文書は，CSS，SVGおよびXSL-FOなどの技術で実現が求められる一般的な日本語組版の要件を記述したものです．この文書は，主としてJIS X 4051（日本語組版規則）に基づいていますが，一部，JIS X 4051に記載されていない事項にも言及しています．この第2版は，見出しの扱い，図版や表の配置，注や合印等の版面デザインに関する多くの情報が増補されています. </dc:description>
```

![ThoriumJapaneseMetadataEncode](https://user-images.githubusercontent.com/625201/71160947-67073b80-2240-11ea-8347-bd872159aa5d.png)

**Comment by danielweck** [comment]
Dear @moongift / Atsushi Nakatsugawa, I found your contact details from this page:
https://tokyo-2019.devrel.net/speakers/atsushi

Could we please obtain a copy of the DevRel EPUB? (just for testing, so that we can check the Unicode encoding of the `package.opf` `dc:description` metadata)

As you can see in the message above (please visit the full GitHub issue tracker if you are reading this in an email notification), other Japanese EPUBs seem to work just fine, so maybe there is a problem in your publication's encoding?

**Comment by llemeurfr** [comment]
Because we had not feedback from the author of the issue, I propose to close this issue. If there is new information available, please re-open it.
