### ISSUE TITLE
Navigation panel does not support RTL

### ISSUE THREAD

**Issue by ways2read** [edrlab/thorium-reader#987]
An EPUB with Arabic content renders correctly in Thorium Reader. However, the headings in the Table of Contents is displayed left to right in the Navigation panel. (screenshot below)

![image](https://user-images.githubusercontent.com/9092859/77847220-39248200-71b3-11ea-90b2-ccd2229b07ab.png)

**Comment by danielweck** [comment]
Although Thorium does not support RTL language scripts yet (Arabic, Hebrew, etc.), I think we can and should implement support for RTL TOC, landmark headings, bookmark labels created from HTML text selection, etc. (basically, any content displayed by the GUI that is tied to the currently-opened publication).

**Comment by ways2read** [comment]
DAISY Consortium (or partners) will be working in two Arabic speaking countries in January 2021. We are writing the content now, and Thorium Reader is selected to be included in the training. It would be great if you can look at RTL support in the UI. We can provide feedback about other aspects of Arabic script in Thorium Reader since the project will run to the end of 2021.

**Comment by danielweck** [comment]
The Right-To-Left mirroring of the user interface controls, even if limited to the navigation panel (i.e. table of contents, bookmarks, etc.) and to the bottom interactive progression bar, is a non-trivial development task in Thorium's existing implementation. I want to look into this problem further in the coming weeks, in order to figure out a pragmatic intermediary solution, for example applying RTL CSS styling to atomic text labels without having to refactor the GUI HTML structure and associated complex CSS stylesheets.

**Comment by llemeurfr** [comment]
Daniel believes this can be achieved for v1.5.

**Comment by danielweck** [comment]
This PR fixes the TOC GUI: https://github.com/edrlab/thorium-reader/pull/1205

There is a pretty significant caveat: in EPUB3 the NavDoc is XHTML with its own "dir" and "lang" markup, but this information is lost when converting to ReadiumWebPubManifest (e.g. TOC is hierarchical list of "link" objects with "title" property for textual label, LANDMARKS is a list of the same link objects, etc.). For example, there is a test Arabic EPUB that has non-RTL French labels in the TOC, which are incorrectly displayed as RTL because of using publication-level dir + lang to determine the direction switch and GUI right-alignment. However we do check for Japanese Vertical Writing Mode which also has RTL page progression direction, to avoid displaying TOC labels incorrectly.

**Comment by danielweck** [comment]
Follow-up issue (RTL support in bottom nav bar): https://github.com/edrlab/thorium-reader/issues/1206
