### ISSUE TITLE
Enhance the implementation of "More information"

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#992]
The modal box is not a good solution (not responsive, rather ugly).

Would it be a good idea to re-implement it as a set of localized EPUB files displayed in the EPUB navigator?

Note: it must not be listed in the personal bookshelf

**Comment by panaC** [comment]
You don't want this to be a dedicated modal window with a static HTML page previously designed as you want ?

**Comment by danielweck** [comment]
In principle, I like the idea of triggering the opening of a "more info" EPUB in a reader window ([dog food](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)) ... but such EPUB would need to be stored in the DB, would have its own ReadiumCSS settings, current reading location, etc. so this would be quite an invasive approach.

> Note: it must not be listed in the personal bookshelf

Yep, the EPUB would need to be blacklisted in the local bookshelf.

So, all in, quite a disruptive technique, with few (if any?) benefits to the end user. In fact, I would be concerned about degradation in usability, due to the overhead of the EPUB interface, slow performance compared with simple Markdown rendering, etc.

**Comment by llemeurfr** [comment]
Could it be seen as an EPUB bundled with the installer? or alternatively as an EPUB available online and downloaded at its first use?

**Comment by llemeurfr** [comment]
We'll certainly do the following: 
- maintain an HTML page per language
- create a RWPL manifest which contains one item in the reading order = the English page + alternates which are the other languages (selectable via a language attribute). 
- A script will package the different pages into a .webpub; this script will be activate at build time. The .webpub will be included into the app resources. It will be imported into the app at first startup.  

to do Laurent -> add precision of alternate languages in the RWPM spec.

**Comment by panaC** [comment]
it is implemented like this:

input:
- an html per languages

output:
- a webpub per language which contains the html in the reading order

this webpub is imported in thorium once time when the user clicks on the 'about' button. And then opened in the reader.

steps: 
- a click on about button dispatch an open dialog action
- this dialog mount the information.tsx component
- the componentDIdMount function checks if the about webpub in the right locale is imported.
- if yes: just opens it
- if no: generates the publication manifest on the fly with the html local pass, imports it and then opens it.
- the reader opens the about webpub

**Comment by llemeurfr** [comment]
These html pages will contain images; we'll store these images in a `images` subfolder on the `/resources/information` folder of the project. 
html pages will reference images via relative paths (./images/xxx.jpg). 

When creating a package, the software will include the images subfolder in the package AND reference each file of the subfolder in the `resources` section of the manifest.
